// Code generated by MockGen. DO NOT EDIT.
// Source: ./clients/clients.go
//
// Generated by this command:
//
//	mockgen -source=./clients/clients.go -destination ./mock/client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	linodego "github.com/linode/linodego"
	gomock "go.uber.org/mock/gomock"
	meta "k8s.io/apimachinery/pkg/api/meta"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockLinodeClient is a mock of LinodeClient interface.
type MockLinodeClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeClientMockRecorder
}

// MockLinodeClientMockRecorder is the mock recorder for MockLinodeClient.
type MockLinodeClientMockRecorder struct {
	mock *MockLinodeClient
}

// NewMockLinodeClient creates a new mock instance.
func NewMockLinodeClient(ctrl *gomock.Controller) *MockLinodeClient {
	mock := &MockLinodeClient{ctrl: ctrl}
	mock.recorder = &MockLinodeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeClient) EXPECT() *MockLinodeClientMockRecorder {
	return m.recorder
}

// BootInstance mocks base method.
func (m *MockLinodeClient) BootInstance(ctx context.Context, linodeID, configID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootInstance", ctx, linodeID, configID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootInstance indicates an expected call of BootInstance.
func (mr *MockLinodeClientMockRecorder) BootInstance(ctx, linodeID, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootInstance", reflect.TypeOf((*MockLinodeClient)(nil).BootInstance), ctx, linodeID, configID)
}

// CreateDomainRecord mocks base method.
func (m *MockLinodeClient) CreateDomainRecord(ctx context.Context, domainID int, recordReq linodego.DomainRecordCreateOptions) (*linodego.DomainRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDomainRecord", ctx, domainID, recordReq)
	ret0, _ := ret[0].(*linodego.DomainRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomainRecord indicates an expected call of CreateDomainRecord.
func (mr *MockLinodeClientMockRecorder) CreateDomainRecord(ctx, domainID, recordReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomainRecord", reflect.TypeOf((*MockLinodeClient)(nil).CreateDomainRecord), ctx, domainID, recordReq)
}

// CreateInstance mocks base method.
func (m *MockLinodeClient) CreateInstance(ctx context.Context, opts linodego.InstanceCreateOptions) (*linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, opts)
	ret0, _ := ret[0].(*linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockLinodeClientMockRecorder) CreateInstance(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockLinodeClient)(nil).CreateInstance), ctx, opts)
}

// CreateInstanceDisk mocks base method.
func (m *MockLinodeClient) CreateInstanceDisk(ctx context.Context, linodeID int, opts linodego.InstanceDiskCreateOptions) (*linodego.InstanceDisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstanceDisk", ctx, linodeID, opts)
	ret0, _ := ret[0].(*linodego.InstanceDisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstanceDisk indicates an expected call of CreateInstanceDisk.
func (mr *MockLinodeClientMockRecorder) CreateInstanceDisk(ctx, linodeID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceDisk", reflect.TypeOf((*MockLinodeClient)(nil).CreateInstanceDisk), ctx, linodeID, opts)
}

// CreateNodeBalancer mocks base method.
func (m *MockLinodeClient) CreateNodeBalancer(ctx context.Context, opts linodego.NodeBalancerCreateOptions) (*linodego.NodeBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeBalancer", ctx, opts)
	ret0, _ := ret[0].(*linodego.NodeBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeBalancer indicates an expected call of CreateNodeBalancer.
func (mr *MockLinodeClientMockRecorder) CreateNodeBalancer(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeBalancer", reflect.TypeOf((*MockLinodeClient)(nil).CreateNodeBalancer), ctx, opts)
}

// CreateNodeBalancerConfig mocks base method.
func (m *MockLinodeClient) CreateNodeBalancerConfig(ctx context.Context, nodebalancerID int, opts linodego.NodeBalancerConfigCreateOptions) (*linodego.NodeBalancerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeBalancerConfig", ctx, nodebalancerID, opts)
	ret0, _ := ret[0].(*linodego.NodeBalancerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeBalancerConfig indicates an expected call of CreateNodeBalancerConfig.
func (mr *MockLinodeClientMockRecorder) CreateNodeBalancerConfig(ctx, nodebalancerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeBalancerConfig", reflect.TypeOf((*MockLinodeClient)(nil).CreateNodeBalancerConfig), ctx, nodebalancerID, opts)
}

// CreateNodeBalancerNode mocks base method.
func (m *MockLinodeClient) CreateNodeBalancerNode(ctx context.Context, nodebalancerID, configID int, opts linodego.NodeBalancerNodeCreateOptions) (*linodego.NodeBalancerNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeBalancerNode", ctx, nodebalancerID, configID, opts)
	ret0, _ := ret[0].(*linodego.NodeBalancerNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeBalancerNode indicates an expected call of CreateNodeBalancerNode.
func (mr *MockLinodeClientMockRecorder) CreateNodeBalancerNode(ctx, nodebalancerID, configID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeBalancerNode", reflect.TypeOf((*MockLinodeClient)(nil).CreateNodeBalancerNode), ctx, nodebalancerID, configID, opts)
}

// CreateObjectStorageBucket mocks base method.
func (m *MockLinodeClient) CreateObjectStorageBucket(ctx context.Context, opts linodego.ObjectStorageBucketCreateOptions) (*linodego.ObjectStorageBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStorageBucket", ctx, opts)
	ret0, _ := ret[0].(*linodego.ObjectStorageBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectStorageBucket indicates an expected call of CreateObjectStorageBucket.
func (mr *MockLinodeClientMockRecorder) CreateObjectStorageBucket(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStorageBucket", reflect.TypeOf((*MockLinodeClient)(nil).CreateObjectStorageBucket), ctx, opts)
}

// CreateObjectStorageKey mocks base method.
func (m *MockLinodeClient) CreateObjectStorageKey(ctx context.Context, opts linodego.ObjectStorageKeyCreateOptions) (*linodego.ObjectStorageKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStorageKey", ctx, opts)
	ret0, _ := ret[0].(*linodego.ObjectStorageKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectStorageKey indicates an expected call of CreateObjectStorageKey.
func (mr *MockLinodeClientMockRecorder) CreateObjectStorageKey(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStorageKey", reflect.TypeOf((*MockLinodeClient)(nil).CreateObjectStorageKey), ctx, opts)
}

// CreateStackscript mocks base method.
func (m *MockLinodeClient) CreateStackscript(ctx context.Context, opts linodego.StackscriptCreateOptions) (*linodego.Stackscript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStackscript", ctx, opts)
	ret0, _ := ret[0].(*linodego.Stackscript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStackscript indicates an expected call of CreateStackscript.
func (mr *MockLinodeClientMockRecorder) CreateStackscript(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStackscript", reflect.TypeOf((*MockLinodeClient)(nil).CreateStackscript), ctx, opts)
}

// CreateVPC mocks base method.
func (m *MockLinodeClient) CreateVPC(ctx context.Context, opts linodego.VPCCreateOptions) (*linodego.VPC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVPC", ctx, opts)
	ret0, _ := ret[0].(*linodego.VPC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVPC indicates an expected call of CreateVPC.
func (mr *MockLinodeClientMockRecorder) CreateVPC(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVPC", reflect.TypeOf((*MockLinodeClient)(nil).CreateVPC), ctx, opts)
}

// DeleteDomainRecord mocks base method.
func (m *MockLinodeClient) DeleteDomainRecord(ctx context.Context, domainID, domainRecordID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDomainRecord", ctx, domainID, domainRecordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDomainRecord indicates an expected call of DeleteDomainRecord.
func (mr *MockLinodeClientMockRecorder) DeleteDomainRecord(ctx, domainID, domainRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDomainRecord", reflect.TypeOf((*MockLinodeClient)(nil).DeleteDomainRecord), ctx, domainID, domainRecordID)
}

// DeleteInstance mocks base method.
func (m *MockLinodeClient) DeleteInstance(ctx context.Context, linodeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, linodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockLinodeClientMockRecorder) DeleteInstance(ctx, linodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockLinodeClient)(nil).DeleteInstance), ctx, linodeID)
}

// DeleteNodeBalancer mocks base method.
func (m *MockLinodeClient) DeleteNodeBalancer(ctx context.Context, nodebalancerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeBalancer", ctx, nodebalancerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeBalancer indicates an expected call of DeleteNodeBalancer.
func (mr *MockLinodeClientMockRecorder) DeleteNodeBalancer(ctx, nodebalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeBalancer", reflect.TypeOf((*MockLinodeClient)(nil).DeleteNodeBalancer), ctx, nodebalancerID)
}

// DeleteNodeBalancerNode mocks base method.
func (m *MockLinodeClient) DeleteNodeBalancerNode(ctx context.Context, nodebalancerID, configID, nodeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeBalancerNode", ctx, nodebalancerID, configID, nodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeBalancerNode indicates an expected call of DeleteNodeBalancerNode.
func (mr *MockLinodeClientMockRecorder) DeleteNodeBalancerNode(ctx, nodebalancerID, configID, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeBalancerNode", reflect.TypeOf((*MockLinodeClient)(nil).DeleteNodeBalancerNode), ctx, nodebalancerID, configID, nodeID)
}

// DeleteObjectStorageKey mocks base method.
func (m *MockLinodeClient) DeleteObjectStorageKey(ctx context.Context, keyID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectStorageKey", ctx, keyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectStorageKey indicates an expected call of DeleteObjectStorageKey.
func (mr *MockLinodeClientMockRecorder) DeleteObjectStorageKey(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectStorageKey", reflect.TypeOf((*MockLinodeClient)(nil).DeleteObjectStorageKey), ctx, keyID)
}

// DeleteVPC mocks base method.
func (m *MockLinodeClient) DeleteVPC(ctx context.Context, vpcID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVPC", ctx, vpcID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVPC indicates an expected call of DeleteVPC.
func (mr *MockLinodeClientMockRecorder) DeleteVPC(ctx, vpcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVPC", reflect.TypeOf((*MockLinodeClient)(nil).DeleteVPC), ctx, vpcID)
}

// GetImage mocks base method.
func (m *MockLinodeClient) GetImage(ctx context.Context, imageID string) (*linodego.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, imageID)
	ret0, _ := ret[0].(*linodego.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockLinodeClientMockRecorder) GetImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockLinodeClient)(nil).GetImage), ctx, imageID)
}

// GetInstance mocks base method.
func (m *MockLinodeClient) GetInstance(ctx context.Context, linodeID int) (*linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, linodeID)
	ret0, _ := ret[0].(*linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockLinodeClientMockRecorder) GetInstance(ctx, linodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockLinodeClient)(nil).GetInstance), ctx, linodeID)
}

// GetInstanceDisk mocks base method.
func (m *MockLinodeClient) GetInstanceDisk(ctx context.Context, linodeID, diskID int) (*linodego.InstanceDisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceDisk", ctx, linodeID, diskID)
	ret0, _ := ret[0].(*linodego.InstanceDisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceDisk indicates an expected call of GetInstanceDisk.
func (mr *MockLinodeClientMockRecorder) GetInstanceDisk(ctx, linodeID, diskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceDisk", reflect.TypeOf((*MockLinodeClient)(nil).GetInstanceDisk), ctx, linodeID, diskID)
}

// GetInstanceIPAddresses mocks base method.
func (m *MockLinodeClient) GetInstanceIPAddresses(ctx context.Context, linodeID int) (*linodego.InstanceIPAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceIPAddresses", ctx, linodeID)
	ret0, _ := ret[0].(*linodego.InstanceIPAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceIPAddresses indicates an expected call of GetInstanceIPAddresses.
func (mr *MockLinodeClientMockRecorder) GetInstanceIPAddresses(ctx, linodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceIPAddresses", reflect.TypeOf((*MockLinodeClient)(nil).GetInstanceIPAddresses), ctx, linodeID)
}

// GetNodeBalancer mocks base method.
func (m *MockLinodeClient) GetNodeBalancer(ctx context.Context, nodebalancerID int) (*linodego.NodeBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeBalancer", ctx, nodebalancerID)
	ret0, _ := ret[0].(*linodego.NodeBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeBalancer indicates an expected call of GetNodeBalancer.
func (mr *MockLinodeClientMockRecorder) GetNodeBalancer(ctx, nodebalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeBalancer", reflect.TypeOf((*MockLinodeClient)(nil).GetNodeBalancer), ctx, nodebalancerID)
}

// GetNodeBalancerConfig mocks base method.
func (m *MockLinodeClient) GetNodeBalancerConfig(ctx context.Context, nodebalancerID, configID int) (*linodego.NodeBalancerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeBalancerConfig", ctx, nodebalancerID, configID)
	ret0, _ := ret[0].(*linodego.NodeBalancerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeBalancerConfig indicates an expected call of GetNodeBalancerConfig.
func (mr *MockLinodeClientMockRecorder) GetNodeBalancerConfig(ctx, nodebalancerID, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeBalancerConfig", reflect.TypeOf((*MockLinodeClient)(nil).GetNodeBalancerConfig), ctx, nodebalancerID, configID)
}

// GetObjectStorageBucket mocks base method.
func (m *MockLinodeClient) GetObjectStorageBucket(ctx context.Context, cluster, label string) (*linodego.ObjectStorageBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStorageBucket", ctx, cluster, label)
	ret0, _ := ret[0].(*linodego.ObjectStorageBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStorageBucket indicates an expected call of GetObjectStorageBucket.
func (mr *MockLinodeClientMockRecorder) GetObjectStorageBucket(ctx, cluster, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStorageBucket", reflect.TypeOf((*MockLinodeClient)(nil).GetObjectStorageBucket), ctx, cluster, label)
}

// GetObjectStorageKey mocks base method.
func (m *MockLinodeClient) GetObjectStorageKey(ctx context.Context, keyID int) (*linodego.ObjectStorageKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStorageKey", ctx, keyID)
	ret0, _ := ret[0].(*linodego.ObjectStorageKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStorageKey indicates an expected call of GetObjectStorageKey.
func (mr *MockLinodeClientMockRecorder) GetObjectStorageKey(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStorageKey", reflect.TypeOf((*MockLinodeClient)(nil).GetObjectStorageKey), ctx, keyID)
}

// GetRegion mocks base method.
func (m *MockLinodeClient) GetRegion(ctx context.Context, regionID string) (*linodego.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, regionID)
	ret0, _ := ret[0].(*linodego.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockLinodeClientMockRecorder) GetRegion(ctx, regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockLinodeClient)(nil).GetRegion), ctx, regionID)
}

// GetType mocks base method.
func (m *MockLinodeClient) GetType(ctx context.Context, typeID string) (*linodego.LinodeType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType", ctx, typeID)
	ret0, _ := ret[0].(*linodego.LinodeType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetType indicates an expected call of GetType.
func (mr *MockLinodeClientMockRecorder) GetType(ctx, typeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockLinodeClient)(nil).GetType), ctx, typeID)
}

// GetVPC mocks base method.
func (m *MockLinodeClient) GetVPC(ctx context.Context, vpcID int) (*linodego.VPC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVPC", ctx, vpcID)
	ret0, _ := ret[0].(*linodego.VPC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVPC indicates an expected call of GetVPC.
func (mr *MockLinodeClientMockRecorder) GetVPC(ctx, vpcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVPC", reflect.TypeOf((*MockLinodeClient)(nil).GetVPC), ctx, vpcID)
}

// ListDomainRecords mocks base method.
func (m *MockLinodeClient) ListDomainRecords(ctx context.Context, domainID int, opts *linodego.ListOptions) ([]linodego.DomainRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDomainRecords", ctx, domainID, opts)
	ret0, _ := ret[0].([]linodego.DomainRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDomainRecords indicates an expected call of ListDomainRecords.
func (mr *MockLinodeClientMockRecorder) ListDomainRecords(ctx, domainID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDomainRecords", reflect.TypeOf((*MockLinodeClient)(nil).ListDomainRecords), ctx, domainID, opts)
}

// ListDomains mocks base method.
func (m *MockLinodeClient) ListDomains(ctx context.Context, opts *linodego.ListOptions) ([]linodego.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDomains", ctx, opts)
	ret0, _ := ret[0].([]linodego.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDomains indicates an expected call of ListDomains.
func (mr *MockLinodeClientMockRecorder) ListDomains(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDomains", reflect.TypeOf((*MockLinodeClient)(nil).ListDomains), ctx, opts)
}

// ListInstanceConfigs mocks base method.
func (m *MockLinodeClient) ListInstanceConfigs(ctx context.Context, linodeID int, opts *linodego.ListOptions) ([]linodego.InstanceConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceConfigs", ctx, linodeID, opts)
	ret0, _ := ret[0].([]linodego.InstanceConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceConfigs indicates an expected call of ListInstanceConfigs.
func (mr *MockLinodeClientMockRecorder) ListInstanceConfigs(ctx, linodeID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceConfigs", reflect.TypeOf((*MockLinodeClient)(nil).ListInstanceConfigs), ctx, linodeID, opts)
}

// ListInstances mocks base method.
func (m *MockLinodeClient) ListInstances(ctx context.Context, opts *linodego.ListOptions) ([]linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, opts)
	ret0, _ := ret[0].([]linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockLinodeClientMockRecorder) ListInstances(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockLinodeClient)(nil).ListInstances), ctx, opts)
}

// ListStackscripts mocks base method.
func (m *MockLinodeClient) ListStackscripts(ctx context.Context, opts *linodego.ListOptions) ([]linodego.Stackscript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStackscripts", ctx, opts)
	ret0, _ := ret[0].([]linodego.Stackscript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStackscripts indicates an expected call of ListStackscripts.
func (mr *MockLinodeClientMockRecorder) ListStackscripts(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStackscripts", reflect.TypeOf((*MockLinodeClient)(nil).ListStackscripts), ctx, opts)
}

// ListVPCs mocks base method.
func (m *MockLinodeClient) ListVPCs(ctx context.Context, opts *linodego.ListOptions) ([]linodego.VPC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVPCs", ctx, opts)
	ret0, _ := ret[0].([]linodego.VPC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVPCs indicates an expected call of ListVPCs.
func (mr *MockLinodeClientMockRecorder) ListVPCs(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVPCs", reflect.TypeOf((*MockLinodeClient)(nil).ListVPCs), ctx, opts)
}

// ResizeInstanceDisk mocks base method.
func (m *MockLinodeClient) ResizeInstanceDisk(ctx context.Context, linodeID, diskID, size int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeInstanceDisk", ctx, linodeID, diskID, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResizeInstanceDisk indicates an expected call of ResizeInstanceDisk.
func (mr *MockLinodeClientMockRecorder) ResizeInstanceDisk(ctx, linodeID, diskID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeInstanceDisk", reflect.TypeOf((*MockLinodeClient)(nil).ResizeInstanceDisk), ctx, linodeID, diskID, size)
}

// UpdateDomainRecord mocks base method.
func (m *MockLinodeClient) UpdateDomainRecord(ctx context.Context, domainID, domainRecordID int, recordReq linodego.DomainRecordUpdateOptions) (*linodego.DomainRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDomainRecord", ctx, domainID, domainRecordID, recordReq)
	ret0, _ := ret[0].(*linodego.DomainRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDomainRecord indicates an expected call of UpdateDomainRecord.
func (mr *MockLinodeClientMockRecorder) UpdateDomainRecord(ctx, domainID, domainRecordID, recordReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomainRecord", reflect.TypeOf((*MockLinodeClient)(nil).UpdateDomainRecord), ctx, domainID, domainRecordID, recordReq)
}

// UpdateInstanceConfig mocks base method.
func (m *MockLinodeClient) UpdateInstanceConfig(ctx context.Context, linodeID, configID int, opts linodego.InstanceConfigUpdateOptions) (*linodego.InstanceConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceConfig", ctx, linodeID, configID, opts)
	ret0, _ := ret[0].(*linodego.InstanceConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstanceConfig indicates an expected call of UpdateInstanceConfig.
func (mr *MockLinodeClientMockRecorder) UpdateInstanceConfig(ctx, linodeID, configID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceConfig", reflect.TypeOf((*MockLinodeClient)(nil).UpdateInstanceConfig), ctx, linodeID, configID, opts)
}

// MockLinodeInstanceClient is a mock of LinodeInstanceClient interface.
type MockLinodeInstanceClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeInstanceClientMockRecorder
}

// MockLinodeInstanceClientMockRecorder is the mock recorder for MockLinodeInstanceClient.
type MockLinodeInstanceClientMockRecorder struct {
	mock *MockLinodeInstanceClient
}

// NewMockLinodeInstanceClient creates a new mock instance.
func NewMockLinodeInstanceClient(ctrl *gomock.Controller) *MockLinodeInstanceClient {
	mock := &MockLinodeInstanceClient{ctrl: ctrl}
	mock.recorder = &MockLinodeInstanceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeInstanceClient) EXPECT() *MockLinodeInstanceClientMockRecorder {
	return m.recorder
}

// BootInstance mocks base method.
func (m *MockLinodeInstanceClient) BootInstance(ctx context.Context, linodeID, configID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootInstance", ctx, linodeID, configID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootInstance indicates an expected call of BootInstance.
func (mr *MockLinodeInstanceClientMockRecorder) BootInstance(ctx, linodeID, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootInstance", reflect.TypeOf((*MockLinodeInstanceClient)(nil).BootInstance), ctx, linodeID, configID)
}

// CreateInstance mocks base method.
func (m *MockLinodeInstanceClient) CreateInstance(ctx context.Context, opts linodego.InstanceCreateOptions) (*linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, opts)
	ret0, _ := ret[0].(*linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockLinodeInstanceClientMockRecorder) CreateInstance(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockLinodeInstanceClient)(nil).CreateInstance), ctx, opts)
}

// CreateInstanceDisk mocks base method.
func (m *MockLinodeInstanceClient) CreateInstanceDisk(ctx context.Context, linodeID int, opts linodego.InstanceDiskCreateOptions) (*linodego.InstanceDisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstanceDisk", ctx, linodeID, opts)
	ret0, _ := ret[0].(*linodego.InstanceDisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstanceDisk indicates an expected call of CreateInstanceDisk.
func (mr *MockLinodeInstanceClientMockRecorder) CreateInstanceDisk(ctx, linodeID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceDisk", reflect.TypeOf((*MockLinodeInstanceClient)(nil).CreateInstanceDisk), ctx, linodeID, opts)
}

// CreateStackscript mocks base method.
func (m *MockLinodeInstanceClient) CreateStackscript(ctx context.Context, opts linodego.StackscriptCreateOptions) (*linodego.Stackscript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStackscript", ctx, opts)
	ret0, _ := ret[0].(*linodego.Stackscript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStackscript indicates an expected call of CreateStackscript.
func (mr *MockLinodeInstanceClientMockRecorder) CreateStackscript(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStackscript", reflect.TypeOf((*MockLinodeInstanceClient)(nil).CreateStackscript), ctx, opts)
}

// DeleteInstance mocks base method.
func (m *MockLinodeInstanceClient) DeleteInstance(ctx context.Context, linodeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, linodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockLinodeInstanceClientMockRecorder) DeleteInstance(ctx, linodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockLinodeInstanceClient)(nil).DeleteInstance), ctx, linodeID)
}

// GetImage mocks base method.
func (m *MockLinodeInstanceClient) GetImage(ctx context.Context, imageID string) (*linodego.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, imageID)
	ret0, _ := ret[0].(*linodego.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockLinodeInstanceClientMockRecorder) GetImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockLinodeInstanceClient)(nil).GetImage), ctx, imageID)
}

// GetInstance mocks base method.
func (m *MockLinodeInstanceClient) GetInstance(ctx context.Context, linodeID int) (*linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, linodeID)
	ret0, _ := ret[0].(*linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockLinodeInstanceClientMockRecorder) GetInstance(ctx, linodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockLinodeInstanceClient)(nil).GetInstance), ctx, linodeID)
}

// GetInstanceDisk mocks base method.
func (m *MockLinodeInstanceClient) GetInstanceDisk(ctx context.Context, linodeID, diskID int) (*linodego.InstanceDisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceDisk", ctx, linodeID, diskID)
	ret0, _ := ret[0].(*linodego.InstanceDisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceDisk indicates an expected call of GetInstanceDisk.
func (mr *MockLinodeInstanceClientMockRecorder) GetInstanceDisk(ctx, linodeID, diskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceDisk", reflect.TypeOf((*MockLinodeInstanceClient)(nil).GetInstanceDisk), ctx, linodeID, diskID)
}

// GetInstanceIPAddresses mocks base method.
func (m *MockLinodeInstanceClient) GetInstanceIPAddresses(ctx context.Context, linodeID int) (*linodego.InstanceIPAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceIPAddresses", ctx, linodeID)
	ret0, _ := ret[0].(*linodego.InstanceIPAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceIPAddresses indicates an expected call of GetInstanceIPAddresses.
func (mr *MockLinodeInstanceClientMockRecorder) GetInstanceIPAddresses(ctx, linodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceIPAddresses", reflect.TypeOf((*MockLinodeInstanceClient)(nil).GetInstanceIPAddresses), ctx, linodeID)
}

// GetRegion mocks base method.
func (m *MockLinodeInstanceClient) GetRegion(ctx context.Context, regionID string) (*linodego.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, regionID)
	ret0, _ := ret[0].(*linodego.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockLinodeInstanceClientMockRecorder) GetRegion(ctx, regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockLinodeInstanceClient)(nil).GetRegion), ctx, regionID)
}

// GetType mocks base method.
func (m *MockLinodeInstanceClient) GetType(ctx context.Context, typeID string) (*linodego.LinodeType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType", ctx, typeID)
	ret0, _ := ret[0].(*linodego.LinodeType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetType indicates an expected call of GetType.
func (mr *MockLinodeInstanceClientMockRecorder) GetType(ctx, typeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockLinodeInstanceClient)(nil).GetType), ctx, typeID)
}

// ListInstanceConfigs mocks base method.
func (m *MockLinodeInstanceClient) ListInstanceConfigs(ctx context.Context, linodeID int, opts *linodego.ListOptions) ([]linodego.InstanceConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceConfigs", ctx, linodeID, opts)
	ret0, _ := ret[0].([]linodego.InstanceConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceConfigs indicates an expected call of ListInstanceConfigs.
func (mr *MockLinodeInstanceClientMockRecorder) ListInstanceConfigs(ctx, linodeID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceConfigs", reflect.TypeOf((*MockLinodeInstanceClient)(nil).ListInstanceConfigs), ctx, linodeID, opts)
}

// ListInstances mocks base method.
func (m *MockLinodeInstanceClient) ListInstances(ctx context.Context, opts *linodego.ListOptions) ([]linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, opts)
	ret0, _ := ret[0].([]linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockLinodeInstanceClientMockRecorder) ListInstances(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockLinodeInstanceClient)(nil).ListInstances), ctx, opts)
}

// ListStackscripts mocks base method.
func (m *MockLinodeInstanceClient) ListStackscripts(ctx context.Context, opts *linodego.ListOptions) ([]linodego.Stackscript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStackscripts", ctx, opts)
	ret0, _ := ret[0].([]linodego.Stackscript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStackscripts indicates an expected call of ListStackscripts.
func (mr *MockLinodeInstanceClientMockRecorder) ListStackscripts(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStackscripts", reflect.TypeOf((*MockLinodeInstanceClient)(nil).ListStackscripts), ctx, opts)
}

// ResizeInstanceDisk mocks base method.
func (m *MockLinodeInstanceClient) ResizeInstanceDisk(ctx context.Context, linodeID, diskID, size int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeInstanceDisk", ctx, linodeID, diskID, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResizeInstanceDisk indicates an expected call of ResizeInstanceDisk.
func (mr *MockLinodeInstanceClientMockRecorder) ResizeInstanceDisk(ctx, linodeID, diskID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeInstanceDisk", reflect.TypeOf((*MockLinodeInstanceClient)(nil).ResizeInstanceDisk), ctx, linodeID, diskID, size)
}

// UpdateInstanceConfig mocks base method.
func (m *MockLinodeInstanceClient) UpdateInstanceConfig(ctx context.Context, linodeID, configID int, opts linodego.InstanceConfigUpdateOptions) (*linodego.InstanceConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceConfig", ctx, linodeID, configID, opts)
	ret0, _ := ret[0].(*linodego.InstanceConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstanceConfig indicates an expected call of UpdateInstanceConfig.
func (mr *MockLinodeInstanceClientMockRecorder) UpdateInstanceConfig(ctx, linodeID, configID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceConfig", reflect.TypeOf((*MockLinodeInstanceClient)(nil).UpdateInstanceConfig), ctx, linodeID, configID, opts)
}

// MockLinodeVPCClient is a mock of LinodeVPCClient interface.
type MockLinodeVPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeVPCClientMockRecorder
}

// MockLinodeVPCClientMockRecorder is the mock recorder for MockLinodeVPCClient.
type MockLinodeVPCClientMockRecorder struct {
	mock *MockLinodeVPCClient
}

// NewMockLinodeVPCClient creates a new mock instance.
func NewMockLinodeVPCClient(ctrl *gomock.Controller) *MockLinodeVPCClient {
	mock := &MockLinodeVPCClient{ctrl: ctrl}
	mock.recorder = &MockLinodeVPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeVPCClient) EXPECT() *MockLinodeVPCClientMockRecorder {
	return m.recorder
}

// CreateVPC mocks base method.
func (m *MockLinodeVPCClient) CreateVPC(ctx context.Context, opts linodego.VPCCreateOptions) (*linodego.VPC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVPC", ctx, opts)
	ret0, _ := ret[0].(*linodego.VPC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVPC indicates an expected call of CreateVPC.
func (mr *MockLinodeVPCClientMockRecorder) CreateVPC(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVPC", reflect.TypeOf((*MockLinodeVPCClient)(nil).CreateVPC), ctx, opts)
}

// DeleteVPC mocks base method.
func (m *MockLinodeVPCClient) DeleteVPC(ctx context.Context, vpcID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVPC", ctx, vpcID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVPC indicates an expected call of DeleteVPC.
func (mr *MockLinodeVPCClientMockRecorder) DeleteVPC(ctx, vpcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVPC", reflect.TypeOf((*MockLinodeVPCClient)(nil).DeleteVPC), ctx, vpcID)
}

// GetVPC mocks base method.
func (m *MockLinodeVPCClient) GetVPC(ctx context.Context, vpcID int) (*linodego.VPC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVPC", ctx, vpcID)
	ret0, _ := ret[0].(*linodego.VPC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVPC indicates an expected call of GetVPC.
func (mr *MockLinodeVPCClientMockRecorder) GetVPC(ctx, vpcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVPC", reflect.TypeOf((*MockLinodeVPCClient)(nil).GetVPC), ctx, vpcID)
}

// ListVPCs mocks base method.
func (m *MockLinodeVPCClient) ListVPCs(ctx context.Context, opts *linodego.ListOptions) ([]linodego.VPC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVPCs", ctx, opts)
	ret0, _ := ret[0].([]linodego.VPC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVPCs indicates an expected call of ListVPCs.
func (mr *MockLinodeVPCClientMockRecorder) ListVPCs(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVPCs", reflect.TypeOf((*MockLinodeVPCClient)(nil).ListVPCs), ctx, opts)
}

// MockLinodeNodeBalancerClient is a mock of LinodeNodeBalancerClient interface.
type MockLinodeNodeBalancerClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeNodeBalancerClientMockRecorder
}

// MockLinodeNodeBalancerClientMockRecorder is the mock recorder for MockLinodeNodeBalancerClient.
type MockLinodeNodeBalancerClientMockRecorder struct {
	mock *MockLinodeNodeBalancerClient
}

// NewMockLinodeNodeBalancerClient creates a new mock instance.
func NewMockLinodeNodeBalancerClient(ctrl *gomock.Controller) *MockLinodeNodeBalancerClient {
	mock := &MockLinodeNodeBalancerClient{ctrl: ctrl}
	mock.recorder = &MockLinodeNodeBalancerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeNodeBalancerClient) EXPECT() *MockLinodeNodeBalancerClientMockRecorder {
	return m.recorder
}

// CreateNodeBalancer mocks base method.
func (m *MockLinodeNodeBalancerClient) CreateNodeBalancer(ctx context.Context, opts linodego.NodeBalancerCreateOptions) (*linodego.NodeBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeBalancer", ctx, opts)
	ret0, _ := ret[0].(*linodego.NodeBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeBalancer indicates an expected call of CreateNodeBalancer.
func (mr *MockLinodeNodeBalancerClientMockRecorder) CreateNodeBalancer(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeBalancer", reflect.TypeOf((*MockLinodeNodeBalancerClient)(nil).CreateNodeBalancer), ctx, opts)
}

// CreateNodeBalancerConfig mocks base method.
func (m *MockLinodeNodeBalancerClient) CreateNodeBalancerConfig(ctx context.Context, nodebalancerID int, opts linodego.NodeBalancerConfigCreateOptions) (*linodego.NodeBalancerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeBalancerConfig", ctx, nodebalancerID, opts)
	ret0, _ := ret[0].(*linodego.NodeBalancerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeBalancerConfig indicates an expected call of CreateNodeBalancerConfig.
func (mr *MockLinodeNodeBalancerClientMockRecorder) CreateNodeBalancerConfig(ctx, nodebalancerID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeBalancerConfig", reflect.TypeOf((*MockLinodeNodeBalancerClient)(nil).CreateNodeBalancerConfig), ctx, nodebalancerID, opts)
}

// CreateNodeBalancerNode mocks base method.
func (m *MockLinodeNodeBalancerClient) CreateNodeBalancerNode(ctx context.Context, nodebalancerID, configID int, opts linodego.NodeBalancerNodeCreateOptions) (*linodego.NodeBalancerNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeBalancerNode", ctx, nodebalancerID, configID, opts)
	ret0, _ := ret[0].(*linodego.NodeBalancerNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeBalancerNode indicates an expected call of CreateNodeBalancerNode.
func (mr *MockLinodeNodeBalancerClientMockRecorder) CreateNodeBalancerNode(ctx, nodebalancerID, configID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeBalancerNode", reflect.TypeOf((*MockLinodeNodeBalancerClient)(nil).CreateNodeBalancerNode), ctx, nodebalancerID, configID, opts)
}

// DeleteNodeBalancer mocks base method.
func (m *MockLinodeNodeBalancerClient) DeleteNodeBalancer(ctx context.Context, nodebalancerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeBalancer", ctx, nodebalancerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeBalancer indicates an expected call of DeleteNodeBalancer.
func (mr *MockLinodeNodeBalancerClientMockRecorder) DeleteNodeBalancer(ctx, nodebalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeBalancer", reflect.TypeOf((*MockLinodeNodeBalancerClient)(nil).DeleteNodeBalancer), ctx, nodebalancerID)
}

// DeleteNodeBalancerNode mocks base method.
func (m *MockLinodeNodeBalancerClient) DeleteNodeBalancerNode(ctx context.Context, nodebalancerID, configID, nodeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeBalancerNode", ctx, nodebalancerID, configID, nodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeBalancerNode indicates an expected call of DeleteNodeBalancerNode.
func (mr *MockLinodeNodeBalancerClientMockRecorder) DeleteNodeBalancerNode(ctx, nodebalancerID, configID, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeBalancerNode", reflect.TypeOf((*MockLinodeNodeBalancerClient)(nil).DeleteNodeBalancerNode), ctx, nodebalancerID, configID, nodeID)
}

// GetNodeBalancer mocks base method.
func (m *MockLinodeNodeBalancerClient) GetNodeBalancer(ctx context.Context, nodebalancerID int) (*linodego.NodeBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeBalancer", ctx, nodebalancerID)
	ret0, _ := ret[0].(*linodego.NodeBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeBalancer indicates an expected call of GetNodeBalancer.
func (mr *MockLinodeNodeBalancerClientMockRecorder) GetNodeBalancer(ctx, nodebalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeBalancer", reflect.TypeOf((*MockLinodeNodeBalancerClient)(nil).GetNodeBalancer), ctx, nodebalancerID)
}

// GetNodeBalancerConfig mocks base method.
func (m *MockLinodeNodeBalancerClient) GetNodeBalancerConfig(ctx context.Context, nodebalancerID, configID int) (*linodego.NodeBalancerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeBalancerConfig", ctx, nodebalancerID, configID)
	ret0, _ := ret[0].(*linodego.NodeBalancerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeBalancerConfig indicates an expected call of GetNodeBalancerConfig.
func (mr *MockLinodeNodeBalancerClientMockRecorder) GetNodeBalancerConfig(ctx, nodebalancerID, configID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeBalancerConfig", reflect.TypeOf((*MockLinodeNodeBalancerClient)(nil).GetNodeBalancerConfig), ctx, nodebalancerID, configID)
}

// MockLinodeObjectStorageClient is a mock of LinodeObjectStorageClient interface.
type MockLinodeObjectStorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeObjectStorageClientMockRecorder
}

// MockLinodeObjectStorageClientMockRecorder is the mock recorder for MockLinodeObjectStorageClient.
type MockLinodeObjectStorageClientMockRecorder struct {
	mock *MockLinodeObjectStorageClient
}

// NewMockLinodeObjectStorageClient creates a new mock instance.
func NewMockLinodeObjectStorageClient(ctrl *gomock.Controller) *MockLinodeObjectStorageClient {
	mock := &MockLinodeObjectStorageClient{ctrl: ctrl}
	mock.recorder = &MockLinodeObjectStorageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeObjectStorageClient) EXPECT() *MockLinodeObjectStorageClientMockRecorder {
	return m.recorder
}

// CreateObjectStorageBucket mocks base method.
func (m *MockLinodeObjectStorageClient) CreateObjectStorageBucket(ctx context.Context, opts linodego.ObjectStorageBucketCreateOptions) (*linodego.ObjectStorageBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStorageBucket", ctx, opts)
	ret0, _ := ret[0].(*linodego.ObjectStorageBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectStorageBucket indicates an expected call of CreateObjectStorageBucket.
func (mr *MockLinodeObjectStorageClientMockRecorder) CreateObjectStorageBucket(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStorageBucket", reflect.TypeOf((*MockLinodeObjectStorageClient)(nil).CreateObjectStorageBucket), ctx, opts)
}

// CreateObjectStorageKey mocks base method.
func (m *MockLinodeObjectStorageClient) CreateObjectStorageKey(ctx context.Context, opts linodego.ObjectStorageKeyCreateOptions) (*linodego.ObjectStorageKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStorageKey", ctx, opts)
	ret0, _ := ret[0].(*linodego.ObjectStorageKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectStorageKey indicates an expected call of CreateObjectStorageKey.
func (mr *MockLinodeObjectStorageClientMockRecorder) CreateObjectStorageKey(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStorageKey", reflect.TypeOf((*MockLinodeObjectStorageClient)(nil).CreateObjectStorageKey), ctx, opts)
}

// DeleteObjectStorageKey mocks base method.
func (m *MockLinodeObjectStorageClient) DeleteObjectStorageKey(ctx context.Context, keyID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectStorageKey", ctx, keyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectStorageKey indicates an expected call of DeleteObjectStorageKey.
func (mr *MockLinodeObjectStorageClientMockRecorder) DeleteObjectStorageKey(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectStorageKey", reflect.TypeOf((*MockLinodeObjectStorageClient)(nil).DeleteObjectStorageKey), ctx, keyID)
}

// GetObjectStorageBucket mocks base method.
func (m *MockLinodeObjectStorageClient) GetObjectStorageBucket(ctx context.Context, cluster, label string) (*linodego.ObjectStorageBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStorageBucket", ctx, cluster, label)
	ret0, _ := ret[0].(*linodego.ObjectStorageBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStorageBucket indicates an expected call of GetObjectStorageBucket.
func (mr *MockLinodeObjectStorageClientMockRecorder) GetObjectStorageBucket(ctx, cluster, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStorageBucket", reflect.TypeOf((*MockLinodeObjectStorageClient)(nil).GetObjectStorageBucket), ctx, cluster, label)
}

// GetObjectStorageKey mocks base method.
func (m *MockLinodeObjectStorageClient) GetObjectStorageKey(ctx context.Context, keyID int) (*linodego.ObjectStorageKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStorageKey", ctx, keyID)
	ret0, _ := ret[0].(*linodego.ObjectStorageKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStorageKey indicates an expected call of GetObjectStorageKey.
func (mr *MockLinodeObjectStorageClientMockRecorder) GetObjectStorageKey(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStorageKey", reflect.TypeOf((*MockLinodeObjectStorageClient)(nil).GetObjectStorageKey), ctx, keyID)
}

// MockLinodeDNSClient is a mock of LinodeDNSClient interface.
type MockLinodeDNSClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeDNSClientMockRecorder
}

// MockLinodeDNSClientMockRecorder is the mock recorder for MockLinodeDNSClient.
type MockLinodeDNSClientMockRecorder struct {
	mock *MockLinodeDNSClient
}

// NewMockLinodeDNSClient creates a new mock instance.
func NewMockLinodeDNSClient(ctrl *gomock.Controller) *MockLinodeDNSClient {
	mock := &MockLinodeDNSClient{ctrl: ctrl}
	mock.recorder = &MockLinodeDNSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodeDNSClient) EXPECT() *MockLinodeDNSClientMockRecorder {
	return m.recorder
}

// CreateDomainRecord mocks base method.
func (m *MockLinodeDNSClient) CreateDomainRecord(ctx context.Context, domainID int, recordReq linodego.DomainRecordCreateOptions) (*linodego.DomainRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDomainRecord", ctx, domainID, recordReq)
	ret0, _ := ret[0].(*linodego.DomainRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomainRecord indicates an expected call of CreateDomainRecord.
func (mr *MockLinodeDNSClientMockRecorder) CreateDomainRecord(ctx, domainID, recordReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomainRecord", reflect.TypeOf((*MockLinodeDNSClient)(nil).CreateDomainRecord), ctx, domainID, recordReq)
}

// DeleteDomainRecord mocks base method.
func (m *MockLinodeDNSClient) DeleteDomainRecord(ctx context.Context, domainID, domainRecordID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDomainRecord", ctx, domainID, domainRecordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDomainRecord indicates an expected call of DeleteDomainRecord.
func (mr *MockLinodeDNSClientMockRecorder) DeleteDomainRecord(ctx, domainID, domainRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDomainRecord", reflect.TypeOf((*MockLinodeDNSClient)(nil).DeleteDomainRecord), ctx, domainID, domainRecordID)
}

// ListDomainRecords mocks base method.
func (m *MockLinodeDNSClient) ListDomainRecords(ctx context.Context, domainID int, opts *linodego.ListOptions) ([]linodego.DomainRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDomainRecords", ctx, domainID, opts)
	ret0, _ := ret[0].([]linodego.DomainRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDomainRecords indicates an expected call of ListDomainRecords.
func (mr *MockLinodeDNSClientMockRecorder) ListDomainRecords(ctx, domainID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDomainRecords", reflect.TypeOf((*MockLinodeDNSClient)(nil).ListDomainRecords), ctx, domainID, opts)
}

// ListDomains mocks base method.
func (m *MockLinodeDNSClient) ListDomains(ctx context.Context, opts *linodego.ListOptions) ([]linodego.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDomains", ctx, opts)
	ret0, _ := ret[0].([]linodego.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDomains indicates an expected call of ListDomains.
func (mr *MockLinodeDNSClientMockRecorder) ListDomains(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDomains", reflect.TypeOf((*MockLinodeDNSClient)(nil).ListDomains), ctx, opts)
}

// UpdateDomainRecord mocks base method.
func (m *MockLinodeDNSClient) UpdateDomainRecord(ctx context.Context, domainID, domainRecordID int, recordReq linodego.DomainRecordUpdateOptions) (*linodego.DomainRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDomainRecord", ctx, domainID, domainRecordID, recordReq)
	ret0, _ := ret[0].(*linodego.DomainRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDomainRecord indicates an expected call of UpdateDomainRecord.
func (mr *MockLinodeDNSClientMockRecorder) UpdateDomainRecord(ctx, domainID, domainRecordID, recordReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomainRecord", reflect.TypeOf((*MockLinodeDNSClient)(nil).UpdateDomainRecord), ctx, domainID, domainRecordID, recordReq)
}

// MockLinodePlacementGroupClient is a mock of LinodePlacementGroupClient interface.
type MockLinodePlacementGroupClient struct {
	ctrl     *gomock.Controller
	recorder *MockLinodePlacementGroupClientMockRecorder
}

// MockLinodePlacementGroupClientMockRecorder is the mock recorder for MockLinodePlacementGroupClient.
type MockLinodePlacementGroupClientMockRecorder struct {
	mock *MockLinodePlacementGroupClient
}

// NewMockLinodePlacementGroupClient creates a new mock instance.
func NewMockLinodePlacementGroupClient(ctrl *gomock.Controller) *MockLinodePlacementGroupClient {
	mock := &MockLinodePlacementGroupClient{ctrl: ctrl}
	mock.recorder = &MockLinodePlacementGroupClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinodePlacementGroupClient) EXPECT() *MockLinodePlacementGroupClientMockRecorder {
	return m.recorder
}

// AssignPlacementGroupLinodes mocks base method.
func (m *MockLinodePlacementGroupClient) AssignPlacementGroupLinodes(ctx context.Context, id int, options linodego.PlacementGroupAssignOptions) (*linodego.PlacementGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPlacementGroupLinodes", ctx, id, options)
	ret0, _ := ret[0].(*linodego.PlacementGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignPlacementGroupLinodes indicates an expected call of AssignPlacementGroupLinodes.
func (mr *MockLinodePlacementGroupClientMockRecorder) AssignPlacementGroupLinodes(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPlacementGroupLinodes", reflect.TypeOf((*MockLinodePlacementGroupClient)(nil).AssignPlacementGroupLinodes), ctx, id, options)
}

// CreatePlacementGroup mocks base method.
func (m *MockLinodePlacementGroupClient) CreatePlacementGroup(ctx context.Context, opts linodego.PlacementGroupCreateOptions) (*linodego.PlacementGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlacementGroup", ctx, opts)
	ret0, _ := ret[0].(*linodego.PlacementGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlacementGroup indicates an expected call of CreatePlacementGroup.
func (mr *MockLinodePlacementGroupClientMockRecorder) CreatePlacementGroup(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlacementGroup", reflect.TypeOf((*MockLinodePlacementGroupClient)(nil).CreatePlacementGroup), ctx, opts)
}

// DeletePlacementGroup mocks base method.
func (m *MockLinodePlacementGroupClient) DeletePlacementGroup(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlacementGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlacementGroup indicates an expected call of DeletePlacementGroup.
func (mr *MockLinodePlacementGroupClientMockRecorder) DeletePlacementGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlacementGroup", reflect.TypeOf((*MockLinodePlacementGroupClient)(nil).DeletePlacementGroup), ctx, id)
}

// GetPlacementGroup mocks base method.
func (m *MockLinodePlacementGroupClient) GetPlacementGroup(ctx context.Context, id int) (*linodego.PlacementGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlacementGroup", ctx, id)
	ret0, _ := ret[0].(*linodego.PlacementGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlacementGroup indicates an expected call of GetPlacementGroup.
func (mr *MockLinodePlacementGroupClientMockRecorder) GetPlacementGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlacementGroup", reflect.TypeOf((*MockLinodePlacementGroupClient)(nil).GetPlacementGroup), ctx, id)
}

// ListPlacementGroups mocks base method.
func (m *MockLinodePlacementGroupClient) ListPlacementGroups(ctx context.Context, options *linodego.ListOptions) ([]linodego.PlacementGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlacementGroups", ctx, options)
	ret0, _ := ret[0].([]linodego.PlacementGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlacementGroups indicates an expected call of ListPlacementGroups.
func (mr *MockLinodePlacementGroupClientMockRecorder) ListPlacementGroups(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlacementGroups", reflect.TypeOf((*MockLinodePlacementGroupClient)(nil).ListPlacementGroups), ctx, options)
}

// UnassignPlacementGroupLinodes mocks base method.
func (m *MockLinodePlacementGroupClient) UnassignPlacementGroupLinodes(ctx context.Context, id int, options linodego.PlacementGroupUnAssignOptions) (*linodego.PlacementGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignPlacementGroupLinodes", ctx, id, options)
	ret0, _ := ret[0].(*linodego.PlacementGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignPlacementGroupLinodes indicates an expected call of UnassignPlacementGroupLinodes.
func (mr *MockLinodePlacementGroupClientMockRecorder) UnassignPlacementGroupLinodes(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignPlacementGroupLinodes", reflect.TypeOf((*MockLinodePlacementGroupClient)(nil).UnassignPlacementGroupLinodes), ctx, id, options)
}

// UpdatePlacementGroup mocks base method.
func (m *MockLinodePlacementGroupClient) UpdatePlacementGroup(ctx context.Context, id int, options linodego.PlacementGroupUpdateOptions) (*linodego.PlacementGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlacementGroup", ctx, id, options)
	ret0, _ := ret[0].(*linodego.PlacementGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlacementGroup indicates an expected call of UpdatePlacementGroup.
func (mr *MockLinodePlacementGroupClientMockRecorder) UpdatePlacementGroup(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlacementGroup", reflect.TypeOf((*MockLinodePlacementGroupClient)(nil).UpdatePlacementGroup), ctx, id, options)
}

// MockK8sClient is a mock of K8sClient interface.
type MockK8sClient struct {
	ctrl     *gomock.Controller
	recorder *MockK8sClientMockRecorder
}

// MockK8sClientMockRecorder is the mock recorder for MockK8sClient.
type MockK8sClientMockRecorder struct {
	mock *MockK8sClient
}

// NewMockK8sClient creates a new mock instance.
func NewMockK8sClient(ctrl *gomock.Controller) *MockK8sClient {
	mock := &MockK8sClient{ctrl: ctrl}
	mock.recorder = &MockK8sClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockK8sClient) EXPECT() *MockK8sClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockK8sClient) Create(ctx context.Context, obj client.Object, opts ...client.CreateOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockK8sClientMockRecorder) Create(ctx, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockK8sClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockK8sClient) Delete(ctx context.Context, obj client.Object, opts ...client.DeleteOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockK8sClientMockRecorder) Delete(ctx, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockK8sClient)(nil).Delete), varargs...)
}

// DeleteAllOf mocks base method.
func (m *MockK8sClient) DeleteAllOf(ctx context.Context, obj client.Object, opts ...client.DeleteAllOfOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAllOf", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllOf indicates an expected call of DeleteAllOf.
func (mr *MockK8sClientMockRecorder) DeleteAllOf(ctx, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllOf", reflect.TypeOf((*MockK8sClient)(nil).DeleteAllOf), varargs...)
}

// Get mocks base method.
func (m *MockK8sClient) Get(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockK8sClientMockRecorder) Get(ctx, key, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockK8sClient)(nil).Get), varargs...)
}

// GroupVersionKindFor mocks base method.
func (m *MockK8sClient) GroupVersionKindFor(obj runtime.Object) (schema.GroupVersionKind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupVersionKindFor", obj)
	ret0, _ := ret[0].(schema.GroupVersionKind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupVersionKindFor indicates an expected call of GroupVersionKindFor.
func (mr *MockK8sClientMockRecorder) GroupVersionKindFor(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupVersionKindFor", reflect.TypeOf((*MockK8sClient)(nil).GroupVersionKindFor), obj)
}

// IsObjectNamespaced mocks base method.
func (m *MockK8sClient) IsObjectNamespaced(obj runtime.Object) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsObjectNamespaced", obj)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsObjectNamespaced indicates an expected call of IsObjectNamespaced.
func (mr *MockK8sClientMockRecorder) IsObjectNamespaced(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsObjectNamespaced", reflect.TypeOf((*MockK8sClient)(nil).IsObjectNamespaced), obj)
}

// List mocks base method.
func (m *MockK8sClient) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, list}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockK8sClientMockRecorder) List(ctx, list any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, list}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockK8sClient)(nil).List), varargs...)
}

// Patch mocks base method.
func (m *MockK8sClient) Patch(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.PatchOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj, patch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockK8sClientMockRecorder) Patch(ctx, obj, patch any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj, patch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockK8sClient)(nil).Patch), varargs...)
}

// RESTMapper mocks base method.
func (m *MockK8sClient) RESTMapper() meta.RESTMapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RESTMapper")
	ret0, _ := ret[0].(meta.RESTMapper)
	return ret0
}

// RESTMapper indicates an expected call of RESTMapper.
func (mr *MockK8sClientMockRecorder) RESTMapper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RESTMapper", reflect.TypeOf((*MockK8sClient)(nil).RESTMapper))
}

// Scheme mocks base method.
func (m *MockK8sClient) Scheme() *runtime.Scheme {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scheme")
	ret0, _ := ret[0].(*runtime.Scheme)
	return ret0
}

// Scheme indicates an expected call of Scheme.
func (mr *MockK8sClientMockRecorder) Scheme() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scheme", reflect.TypeOf((*MockK8sClient)(nil).Scheme))
}

// Status mocks base method.
func (m *MockK8sClient) Status() client.SubResourceWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(client.SubResourceWriter)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockK8sClientMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockK8sClient)(nil).Status))
}

// SubResource mocks base method.
func (m *MockK8sClient) SubResource(subResource string) client.SubResourceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubResource", subResource)
	ret0, _ := ret[0].(client.SubResourceClient)
	return ret0
}

// SubResource indicates an expected call of SubResource.
func (mr *MockK8sClientMockRecorder) SubResource(subResource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubResource", reflect.TypeOf((*MockK8sClient)(nil).SubResource), subResource)
}

// Update mocks base method.
func (m *MockK8sClient) Update(ctx context.Context, obj client.Object, opts ...client.UpdateOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockK8sClientMockRecorder) Update(ctx, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockK8sClient)(nil).Update), varargs...)
}
