// Code generated by gowrap. DO NOT EDIT.
// template: ../../../hack/templates/opentelemetry.go.gotpl
// gowrap: http://github.com/hexdigest/gowrap

package linodeclient

//go:generate gowrap gen -p github.com/linode/cluster-api-provider-linode/clients -i LinodeClient -t ../../../hack/templates/opentelemetry.go.gotpl -o linodeclient.gen.go -l ""

import (
	"context"

	_sourceClients "github.com/linode/cluster-api-provider-linode/clients"
	"github.com/linode/cluster-api-provider-linode/observability/tracing"
	"github.com/linode/linodego"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// LinodeClientWithTracing implements _sourceClients.LinodeClient interface instrumented with opentracing spans
type LinodeClientWithTracing struct {
	_sourceClients.LinodeClient
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewLinodeClientWithTracing returns LinodeClientWithTracing
func NewLinodeClientWithTracing(base _sourceClients.LinodeClient, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) LinodeClientWithTracing {
	d := LinodeClientWithTracing{
		LinodeClient: base,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// AssignPlacementGroupLinodes implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) AssignPlacementGroupLinodes(ctx context.Context, id int, options linodego.PlacementGroupAssignOptions) (pp1 *linodego.PlacementGroup, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.AssignPlacementGroupLinodes")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"id":      id,
				"options": options}, map[string]interface{}{
				"pp1": pp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.AssignPlacementGroupLinodes(ctx, id, options)
}

// BootInstance implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) BootInstance(ctx context.Context, linodeID int, configID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.BootInstance")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"configID": configID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.BootInstance(ctx, linodeID, configID)
}

// CreateDomainRecord implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateDomainRecord(ctx context.Context, domainID int, recordReq linodego.DomainRecordCreateOptions) (dp1 *linodego.DomainRecord, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateDomainRecord")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"domainID":  domainID,
				"recordReq": recordReq}, map[string]interface{}{
				"dp1": dp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateDomainRecord(ctx, domainID, recordReq)
}

// CreateFirewall implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateFirewall(ctx context.Context, opts linodego.FirewallCreateOptions) (fp1 *linodego.Firewall, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateFirewall")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"fp1": fp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateFirewall(ctx, opts)
}

// CreateInstance implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateInstance(ctx context.Context, opts linodego.InstanceCreateOptions) (ip1 *linodego.Instance, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateInstance")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateInstance(ctx, opts)
}

// CreateInstanceDisk implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateInstanceDisk(ctx context.Context, linodeID int, opts linodego.InstanceDiskCreateOptions) (ip1 *linodego.InstanceDisk, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateInstanceDisk")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"opts":     opts}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateInstanceDisk(ctx, linodeID, opts)
}

// CreateNodeBalancer implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateNodeBalancer(ctx context.Context, opts linodego.NodeBalancerCreateOptions) (np1 *linodego.NodeBalancer, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateNodeBalancer")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"np1": np1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateNodeBalancer(ctx, opts)
}

// CreateNodeBalancerConfig implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateNodeBalancerConfig(ctx context.Context, nodebalancerID int, opts linodego.NodeBalancerConfigCreateOptions) (np1 *linodego.NodeBalancerConfig, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateNodeBalancerConfig")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"nodebalancerID": nodebalancerID,
				"opts":           opts}, map[string]interface{}{
				"np1": np1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateNodeBalancerConfig(ctx, nodebalancerID, opts)
}

// CreateNodeBalancerNode implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateNodeBalancerNode(ctx context.Context, nodebalancerID int, configID int, opts linodego.NodeBalancerNodeCreateOptions) (np1 *linodego.NodeBalancerNode, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateNodeBalancerNode")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"nodebalancerID": nodebalancerID,
				"configID":       configID,
				"opts":           opts}, map[string]interface{}{
				"np1": np1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateNodeBalancerNode(ctx, nodebalancerID, configID, opts)
}

// CreateObjectStorageBucket implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateObjectStorageBucket(ctx context.Context, opts linodego.ObjectStorageBucketCreateOptions) (op1 *linodego.ObjectStorageBucket, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateObjectStorageBucket")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"op1": op1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateObjectStorageBucket(ctx, opts)
}

// CreateObjectStorageKey implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateObjectStorageKey(ctx context.Context, opts linodego.ObjectStorageKeyCreateOptions) (op1 *linodego.ObjectStorageKey, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateObjectStorageKey")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"op1": op1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateObjectStorageKey(ctx, opts)
}

// CreatePlacementGroup implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreatePlacementGroup(ctx context.Context, opts linodego.PlacementGroupCreateOptions) (pp1 *linodego.PlacementGroup, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreatePlacementGroup")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"pp1": pp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreatePlacementGroup(ctx, opts)
}

// CreateVPC implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateVPC(ctx context.Context, opts linodego.VPCCreateOptions) (vp1 *linodego.VPC, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateVPC")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"vp1": vp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateVPC(ctx, opts)
}

// CreateVPCSubnet implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) CreateVPCSubnet(ctx context.Context, opts linodego.VPCSubnetCreateOptions, vpcID int) (vp1 *linodego.VPCSubnet, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.CreateVPCSubnet")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"opts":  opts,
				"vpcID": vpcID}, map[string]interface{}{
				"vp1": vp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.CreateVPCSubnet(ctx, opts, vpcID)
}

// DeleteDomainRecord implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteDomainRecord(ctx context.Context, domainID int, domainRecordID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteDomainRecord")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"domainID":       domainID,
				"domainRecordID": domainRecordID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteDomainRecord(ctx, domainID, domainRecordID)
}

// DeleteFirewall implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteFirewall(ctx context.Context, firewallID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteFirewall")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"firewallID": firewallID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteFirewall(ctx, firewallID)
}

// DeleteFirewallDevice implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteFirewallDevice(ctx context.Context, firewallID int, deviceID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteFirewallDevice")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"firewallID": firewallID,
				"deviceID":   deviceID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteFirewallDevice(ctx, firewallID, deviceID)
}

// DeleteInstance implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteInstance(ctx context.Context, linodeID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteInstance")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteInstance(ctx, linodeID)
}

// DeleteNodeBalancer implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteNodeBalancer(ctx context.Context, nodebalancerID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteNodeBalancer")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"nodebalancerID": nodebalancerID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteNodeBalancer(ctx, nodebalancerID)
}

// DeleteNodeBalancerNode implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteNodeBalancerNode(ctx context.Context, nodebalancerID int, configID int, nodeID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteNodeBalancerNode")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"nodebalancerID": nodebalancerID,
				"configID":       configID,
				"nodeID":         nodeID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteNodeBalancerNode(ctx, nodebalancerID, configID, nodeID)
}

// DeleteObjectStorageBucket implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteObjectStorageBucket(ctx context.Context, regionID string, label string) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteObjectStorageBucket")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"regionID": regionID,
				"label":    label}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteObjectStorageBucket(ctx, regionID, label)
}

// DeleteObjectStorageKey implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteObjectStorageKey(ctx context.Context, keyID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteObjectStorageKey")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"keyID": keyID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteObjectStorageKey(ctx, keyID)
}

// DeletePlacementGroup implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeletePlacementGroup(ctx context.Context, id int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeletePlacementGroup")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeletePlacementGroup(ctx, id)
}

// DeleteVPC implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteVPC(ctx context.Context, vpcID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteVPC")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"vpcID": vpcID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteVPC(ctx, vpcID)
}

// DeleteVPCSubnet implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) DeleteVPCSubnet(ctx context.Context, vpcID int, subnetID int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.DeleteVPCSubnet")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"vpcID":    vpcID,
				"subnetID": subnetID}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.DeleteVPCSubnet(ctx, vpcID, subnetID)
}

// GetFirewall implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetFirewall(ctx context.Context, firewallID int) (fp1 *linodego.Firewall, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetFirewall")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"firewallID": firewallID}, map[string]interface{}{
				"fp1": fp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetFirewall(ctx, firewallID)
}

// GetFirewallDevice implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetFirewallDevice(ctx context.Context, firewallID int, deviceID int) (fp1 *linodego.FirewallDevice, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetFirewallDevice")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"firewallID": firewallID,
				"deviceID":   deviceID}, map[string]interface{}{
				"fp1": fp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetFirewallDevice(ctx, firewallID, deviceID)
}

// GetFirewallRules implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetFirewallRules(ctx context.Context, firewallID int) (fp1 *linodego.FirewallRuleSet, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetFirewallRules")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"firewallID": firewallID}, map[string]interface{}{
				"fp1": fp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetFirewallRules(ctx, firewallID)
}

// GetImage implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetImage(ctx context.Context, imageID string) (ip1 *linodego.Image, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetImage")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"imageID": imageID}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetImage(ctx, imageID)
}

// GetInstance implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetInstance(ctx context.Context, linodeID int) (ip1 *linodego.Instance, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetInstance")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetInstance(ctx, linodeID)
}

// GetInstanceDisk implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetInstanceDisk(ctx context.Context, linodeID int, diskID int) (ip1 *linodego.InstanceDisk, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetInstanceDisk")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"diskID":   diskID}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetInstanceDisk(ctx, linodeID, diskID)
}

// GetInstanceIPAddresses implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetInstanceIPAddresses(ctx context.Context, linodeID int) (ip1 *linodego.InstanceIPAddressResponse, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetInstanceIPAddresses")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetInstanceIPAddresses(ctx, linodeID)
}

// GetNodeBalancer implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetNodeBalancer(ctx context.Context, nodebalancerID int) (np1 *linodego.NodeBalancer, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetNodeBalancer")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"nodebalancerID": nodebalancerID}, map[string]interface{}{
				"np1": np1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetNodeBalancer(ctx, nodebalancerID)
}

// GetNodeBalancerConfig implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetNodeBalancerConfig(ctx context.Context, nodebalancerID int, configID int) (np1 *linodego.NodeBalancerConfig, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetNodeBalancerConfig")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"nodebalancerID": nodebalancerID,
				"configID":       configID}, map[string]interface{}{
				"np1": np1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetNodeBalancerConfig(ctx, nodebalancerID, configID)
}

// GetObjectStorageBucket implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetObjectStorageBucket(ctx context.Context, regionID string, label string) (op1 *linodego.ObjectStorageBucket, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetObjectStorageBucket")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"regionID": regionID,
				"label":    label}, map[string]interface{}{
				"op1": op1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetObjectStorageBucket(ctx, regionID, label)
}

// GetObjectStorageBucketAccess implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetObjectStorageBucketAccess(ctx context.Context, clusterOrRegionID string, label string) (op1 *linodego.ObjectStorageBucketAccess, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetObjectStorageBucketAccess")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":               ctx,
				"clusterOrRegionID": clusterOrRegionID,
				"label":             label}, map[string]interface{}{
				"op1": op1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetObjectStorageBucketAccess(ctx, clusterOrRegionID, label)
}

// GetObjectStorageKey implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetObjectStorageKey(ctx context.Context, keyID int) (op1 *linodego.ObjectStorageKey, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetObjectStorageKey")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"keyID": keyID}, map[string]interface{}{
				"op1": op1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetObjectStorageKey(ctx, keyID)
}

// GetPlacementGroup implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetPlacementGroup(ctx context.Context, id int) (pp1 *linodego.PlacementGroup, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetPlacementGroup")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"pp1": pp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetPlacementGroup(ctx, id)
}

// GetRegion implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetRegion(ctx context.Context, regionID string) (rp1 *linodego.Region, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetRegion")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"regionID": regionID}, map[string]interface{}{
				"rp1": rp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetRegion(ctx, regionID)
}

// GetType implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetType(ctx context.Context, typeID string) (lp1 *linodego.LinodeType, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetType")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"typeID": typeID}, map[string]interface{}{
				"lp1": lp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetType(ctx, typeID)
}

// GetVPC implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) GetVPC(ctx context.Context, vpcID int) (vp1 *linodego.VPC, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.GetVPC")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"vpcID": vpcID}, map[string]interface{}{
				"vp1": vp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.GetVPC(ctx, vpcID)
}

// ListDomainRecords implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListDomainRecords(ctx context.Context, domainID int, opts *linodego.ListOptions) (da1 []linodego.DomainRecord, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListDomainRecords")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"domainID": domainID,
				"opts":     opts}, map[string]interface{}{
				"da1": da1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListDomainRecords(ctx, domainID, opts)
}

// ListDomains implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListDomains(ctx context.Context, opts *linodego.ListOptions) (da1 []linodego.Domain, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListDomains")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"da1": da1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListDomains(ctx, opts)
}

// ListInstanceConfigs implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListInstanceConfigs(ctx context.Context, linodeID int, opts *linodego.ListOptions) (ia1 []linodego.InstanceConfig, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListInstanceConfigs")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"opts":     opts}, map[string]interface{}{
				"ia1": ia1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListInstanceConfigs(ctx, linodeID, opts)
}

// ListInstanceFirewalls implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListInstanceFirewalls(ctx context.Context, linodeID int, opts *linodego.ListOptions) (fa1 []linodego.Firewall, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListInstanceFirewalls")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"opts":     opts}, map[string]interface{}{
				"fa1": fa1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListInstanceFirewalls(ctx, linodeID, opts)
}

// ListInstances implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListInstances(ctx context.Context, opts *linodego.ListOptions) (ia1 []linodego.Instance, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListInstances")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"ia1": ia1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListInstances(ctx, opts)
}

// ListNodeBalancerNodes implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListNodeBalancerNodes(ctx context.Context, nodebalancerID int, configID int, opts *linodego.ListOptions) (na1 []linodego.NodeBalancerNode, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListNodeBalancerNodes")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"nodebalancerID": nodebalancerID,
				"configID":       configID,
				"opts":           opts}, map[string]interface{}{
				"na1": na1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListNodeBalancerNodes(ctx, nodebalancerID, configID, opts)
}

// ListPlacementGroups implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListPlacementGroups(ctx context.Context, options *linodego.ListOptions) (pa1 []linodego.PlacementGroup, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListPlacementGroups")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"options": options}, map[string]interface{}{
				"pa1": pa1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListPlacementGroups(ctx, options)
}

// ListVPCs implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ListVPCs(ctx context.Context, opts *linodego.ListOptions) (va1 []linodego.VPC, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ListVPCs")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"opts": opts}, map[string]interface{}{
				"va1": va1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ListVPCs(ctx, opts)
}

// ResizeInstanceDisk implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) ResizeInstanceDisk(ctx context.Context, linodeID int, diskID int, size int) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.ResizeInstanceDisk")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"diskID":   diskID,
				"size":     size}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.ResizeInstanceDisk(ctx, linodeID, diskID, size)
}

// UnassignPlacementGroupLinodes implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UnassignPlacementGroupLinodes(ctx context.Context, id int, options linodego.PlacementGroupUnAssignOptions) (pp1 *linodego.PlacementGroup, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UnassignPlacementGroupLinodes")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"id":      id,
				"options": options}, map[string]interface{}{
				"pp1": pp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UnassignPlacementGroupLinodes(ctx, id, options)
}

// UpdateDomainRecord implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdateDomainRecord(ctx context.Context, domainID int, domainRecordID int, recordReq linodego.DomainRecordUpdateOptions) (dp1 *linodego.DomainRecord, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdateDomainRecord")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"domainID":       domainID,
				"domainRecordID": domainRecordID,
				"recordReq":      recordReq}, map[string]interface{}{
				"dp1": dp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdateDomainRecord(ctx, domainID, domainRecordID, recordReq)
}

// UpdateFirewall implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdateFirewall(ctx context.Context, firewallID int, opts linodego.FirewallUpdateOptions) (fp1 *linodego.Firewall, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdateFirewall")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"firewallID": firewallID,
				"opts":       opts}, map[string]interface{}{
				"fp1": fp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdateFirewall(ctx, firewallID, opts)
}

// UpdateFirewallRules implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdateFirewallRules(ctx context.Context, firewallID int, rules linodego.FirewallRuleSet) (fp1 *linodego.FirewallRuleSet, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdateFirewallRules")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"firewallID": firewallID,
				"rules":      rules}, map[string]interface{}{
				"fp1": fp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdateFirewallRules(ctx, firewallID, rules)
}

// UpdateInstance implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdateInstance(ctx context.Context, linodeId int, opts linodego.InstanceUpdateOptions) (ip1 *linodego.Instance, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdateInstance")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeId": linodeId,
				"opts":     opts}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdateInstance(ctx, linodeId, opts)
}

// UpdateInstanceConfig implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdateInstanceConfig(ctx context.Context, linodeID int, configID int, opts linodego.InstanceConfigUpdateOptions) (ip1 *linodego.InstanceConfig, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdateInstanceConfig")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"configID": configID,
				"opts":     opts}, map[string]interface{}{
				"ip1": ip1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdateInstanceConfig(ctx, linodeID, configID, opts)
}

// UpdateInstanceFirewalls implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdateInstanceFirewalls(ctx context.Context, linodeID int, opts linodego.InstanceFirewallUpdateOptions) (fa1 []linodego.Firewall, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdateInstanceFirewalls")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"linodeID": linodeID,
				"opts":     opts}, map[string]interface{}{
				"fa1": fa1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdateInstanceFirewalls(ctx, linodeID, opts)
}

// UpdateObjectStorageBucketAccess implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdateObjectStorageBucketAccess(ctx context.Context, clusterOrRegionID string, label string, opts linodego.ObjectStorageBucketUpdateAccessOptions) (err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdateObjectStorageBucketAccess")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":               ctx,
				"clusterOrRegionID": clusterOrRegionID,
				"label":             label,
				"opts":              opts}, map[string]interface{}{
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdateObjectStorageBucketAccess(ctx, clusterOrRegionID, label, opts)
}

// UpdatePlacementGroup implements _sourceClients.LinodeClient
func (_d LinodeClientWithTracing) UpdatePlacementGroup(ctx context.Context, id int, options linodego.PlacementGroupUpdateOptions) (pp1 *linodego.PlacementGroup, err error) {
	ctx, _span := tracing.Start(ctx, "_sourceClients.LinodeClient.UpdatePlacementGroup")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"id":      id,
				"options": options}, map[string]interface{}{
				"pp1": pp1,
				"err": err})
		}

		if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.LinodeClient.UpdatePlacementGroup(ctx, id, options)
}
