//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Akamai Technologies, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/linode/cluster-api-provider-linode/api/v1alpha2"
	linodego "github.com/linode/linodego"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*InstanceConfigInterfaceCreateOptions)(nil), (*v1alpha2.InstanceConfigInterfaceCreateOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstanceConfigInterfaceCreateOptions_To_v1alpha2_InstanceConfigInterfaceCreateOptions(a.(*InstanceConfigInterfaceCreateOptions), b.(*v1alpha2.InstanceConfigInterfaceCreateOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InstanceConfigInterfaceCreateOptions)(nil), (*InstanceConfigInterfaceCreateOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InstanceConfigInterfaceCreateOptions_To_v1alpha1_InstanceConfigInterfaceCreateOptions(a.(*v1alpha2.InstanceConfigInterfaceCreateOptions), b.(*InstanceConfigInterfaceCreateOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceDisk)(nil), (*v1alpha2.InstanceDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstanceDisk_To_v1alpha2_InstanceDisk(a.(*InstanceDisk), b.(*v1alpha2.InstanceDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InstanceDisk)(nil), (*InstanceDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InstanceDisk_To_v1alpha1_InstanceDisk(a.(*v1alpha2.InstanceDisk), b.(*InstanceDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceMetadataOptions)(nil), (*v1alpha2.InstanceMetadataOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstanceMetadataOptions_To_v1alpha2_InstanceMetadataOptions(a.(*InstanceMetadataOptions), b.(*v1alpha2.InstanceMetadataOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InstanceMetadataOptions)(nil), (*InstanceMetadataOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(a.(*v1alpha2.InstanceMetadataOptions), b.(*InstanceMetadataOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeCluster)(nil), (*v1alpha2.LinodeCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeCluster_To_v1alpha2_LinodeCluster(a.(*LinodeCluster), b.(*v1alpha2.LinodeCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeCluster)(nil), (*LinodeCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeCluster_To_v1alpha1_LinodeCluster(a.(*v1alpha2.LinodeCluster), b.(*LinodeCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeClusterList)(nil), (*v1alpha2.LinodeClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeClusterList_To_v1alpha2_LinodeClusterList(a.(*LinodeClusterList), b.(*v1alpha2.LinodeClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeClusterList)(nil), (*LinodeClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeClusterList_To_v1alpha1_LinodeClusterList(a.(*v1alpha2.LinodeClusterList), b.(*LinodeClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeClusterSpec)(nil), (*v1alpha2.LinodeClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeClusterSpec_To_v1alpha2_LinodeClusterSpec(a.(*LinodeClusterSpec), b.(*v1alpha2.LinodeClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeClusterSpec)(nil), (*LinodeClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeClusterSpec_To_v1alpha1_LinodeClusterSpec(a.(*v1alpha2.LinodeClusterSpec), b.(*LinodeClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeClusterStatus)(nil), (*v1alpha2.LinodeClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeClusterStatus_To_v1alpha2_LinodeClusterStatus(a.(*LinodeClusterStatus), b.(*v1alpha2.LinodeClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeClusterStatus)(nil), (*LinodeClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeClusterStatus_To_v1alpha1_LinodeClusterStatus(a.(*v1alpha2.LinodeClusterStatus), b.(*LinodeClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeClusterTemplate)(nil), (*v1alpha2.LinodeClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeClusterTemplate_To_v1alpha2_LinodeClusterTemplate(a.(*LinodeClusterTemplate), b.(*v1alpha2.LinodeClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeClusterTemplate)(nil), (*LinodeClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeClusterTemplate_To_v1alpha1_LinodeClusterTemplate(a.(*v1alpha2.LinodeClusterTemplate), b.(*LinodeClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeClusterTemplateList)(nil), (*v1alpha2.LinodeClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeClusterTemplateList_To_v1alpha2_LinodeClusterTemplateList(a.(*LinodeClusterTemplateList), b.(*v1alpha2.LinodeClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeClusterTemplateList)(nil), (*LinodeClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeClusterTemplateList_To_v1alpha1_LinodeClusterTemplateList(a.(*v1alpha2.LinodeClusterTemplateList), b.(*LinodeClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeClusterTemplateResource)(nil), (*v1alpha2.LinodeClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeClusterTemplateResource_To_v1alpha2_LinodeClusterTemplateResource(a.(*LinodeClusterTemplateResource), b.(*v1alpha2.LinodeClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeClusterTemplateResource)(nil), (*LinodeClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeClusterTemplateResource_To_v1alpha1_LinodeClusterTemplateResource(a.(*v1alpha2.LinodeClusterTemplateResource), b.(*LinodeClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeClusterTemplateSpec)(nil), (*v1alpha2.LinodeClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeClusterTemplateSpec_To_v1alpha2_LinodeClusterTemplateSpec(a.(*LinodeClusterTemplateSpec), b.(*v1alpha2.LinodeClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeClusterTemplateSpec)(nil), (*LinodeClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeClusterTemplateSpec_To_v1alpha1_LinodeClusterTemplateSpec(a.(*v1alpha2.LinodeClusterTemplateSpec), b.(*LinodeClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachine)(nil), (*v1alpha2.LinodeMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachine_To_v1alpha2_LinodeMachine(a.(*LinodeMachine), b.(*v1alpha2.LinodeMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeMachine)(nil), (*LinodeMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachine_To_v1alpha1_LinodeMachine(a.(*v1alpha2.LinodeMachine), b.(*LinodeMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachineList)(nil), (*v1alpha2.LinodeMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachineList_To_v1alpha2_LinodeMachineList(a.(*LinodeMachineList), b.(*v1alpha2.LinodeMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeMachineList)(nil), (*LinodeMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachineList_To_v1alpha1_LinodeMachineList(a.(*v1alpha2.LinodeMachineList), b.(*LinodeMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachineSpec)(nil), (*v1alpha2.LinodeMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachineSpec_To_v1alpha2_LinodeMachineSpec(a.(*LinodeMachineSpec), b.(*v1alpha2.LinodeMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachineStatus)(nil), (*v1alpha2.LinodeMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachineStatus_To_v1alpha2_LinodeMachineStatus(a.(*LinodeMachineStatus), b.(*v1alpha2.LinodeMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeMachineStatus)(nil), (*LinodeMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachineStatus_To_v1alpha1_LinodeMachineStatus(a.(*v1alpha2.LinodeMachineStatus), b.(*LinodeMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachineTemplate)(nil), (*v1alpha2.LinodeMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachineTemplate_To_v1alpha2_LinodeMachineTemplate(a.(*LinodeMachineTemplate), b.(*v1alpha2.LinodeMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeMachineTemplate)(nil), (*LinodeMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachineTemplate_To_v1alpha1_LinodeMachineTemplate(a.(*v1alpha2.LinodeMachineTemplate), b.(*LinodeMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachineTemplateList)(nil), (*v1alpha2.LinodeMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachineTemplateList_To_v1alpha2_LinodeMachineTemplateList(a.(*LinodeMachineTemplateList), b.(*v1alpha2.LinodeMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeMachineTemplateList)(nil), (*LinodeMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachineTemplateList_To_v1alpha1_LinodeMachineTemplateList(a.(*v1alpha2.LinodeMachineTemplateList), b.(*LinodeMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachineTemplateResource)(nil), (*v1alpha2.LinodeMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachineTemplateResource_To_v1alpha2_LinodeMachineTemplateResource(a.(*LinodeMachineTemplateResource), b.(*v1alpha2.LinodeMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeMachineTemplateResource)(nil), (*LinodeMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachineTemplateResource_To_v1alpha1_LinodeMachineTemplateResource(a.(*v1alpha2.LinodeMachineTemplateResource), b.(*LinodeMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeMachineTemplateSpec)(nil), (*v1alpha2.LinodeMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeMachineTemplateSpec_To_v1alpha2_LinodeMachineTemplateSpec(a.(*LinodeMachineTemplateSpec), b.(*v1alpha2.LinodeMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeMachineTemplateSpec)(nil), (*LinodeMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachineTemplateSpec_To_v1alpha1_LinodeMachineTemplateSpec(a.(*v1alpha2.LinodeMachineTemplateSpec), b.(*LinodeMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeObjectStorageBucket)(nil), (*v1alpha2.LinodeObjectStorageBucket)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeObjectStorageBucket_To_v1alpha2_LinodeObjectStorageBucket(a.(*LinodeObjectStorageBucket), b.(*v1alpha2.LinodeObjectStorageBucket), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeObjectStorageBucketList)(nil), (*v1alpha2.LinodeObjectStorageBucketList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeObjectStorageBucketList_To_v1alpha2_LinodeObjectStorageBucketList(a.(*LinodeObjectStorageBucketList), b.(*v1alpha2.LinodeObjectStorageBucketList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeObjectStorageBucketList)(nil), (*LinodeObjectStorageBucketList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeObjectStorageBucketList_To_v1alpha1_LinodeObjectStorageBucketList(a.(*v1alpha2.LinodeObjectStorageBucketList), b.(*LinodeObjectStorageBucketList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeObjectStorageBucketStatus)(nil), (*v1alpha2.LinodeObjectStorageBucketStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeObjectStorageBucketStatus_To_v1alpha2_LinodeObjectStorageBucketStatus(a.(*LinodeObjectStorageBucketStatus), b.(*v1alpha2.LinodeObjectStorageBucketStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeObjectStorageBucketStatus)(nil), (*LinodeObjectStorageBucketStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeObjectStorageBucketStatus_To_v1alpha1_LinodeObjectStorageBucketStatus(a.(*v1alpha2.LinodeObjectStorageBucketStatus), b.(*LinodeObjectStorageBucketStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeVPC)(nil), (*v1alpha2.LinodeVPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeVPC_To_v1alpha2_LinodeVPC(a.(*LinodeVPC), b.(*v1alpha2.LinodeVPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeVPC)(nil), (*LinodeVPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeVPC_To_v1alpha1_LinodeVPC(a.(*v1alpha2.LinodeVPC), b.(*LinodeVPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeVPCList)(nil), (*v1alpha2.LinodeVPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeVPCList_To_v1alpha2_LinodeVPCList(a.(*LinodeVPCList), b.(*v1alpha2.LinodeVPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeVPCList)(nil), (*LinodeVPCList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeVPCList_To_v1alpha1_LinodeVPCList(a.(*v1alpha2.LinodeVPCList), b.(*LinodeVPCList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeVPCSpec)(nil), (*v1alpha2.LinodeVPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeVPCSpec_To_v1alpha2_LinodeVPCSpec(a.(*LinodeVPCSpec), b.(*v1alpha2.LinodeVPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeVPCSpec)(nil), (*LinodeVPCSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeVPCSpec_To_v1alpha1_LinodeVPCSpec(a.(*v1alpha2.LinodeVPCSpec), b.(*LinodeVPCSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LinodeVPCStatus)(nil), (*v1alpha2.LinodeVPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeVPCStatus_To_v1alpha2_LinodeVPCStatus(a.(*LinodeVPCStatus), b.(*v1alpha2.LinodeVPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.LinodeVPCStatus)(nil), (*LinodeVPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeVPCStatus_To_v1alpha1_LinodeVPCStatus(a.(*v1alpha2.LinodeVPCStatus), b.(*LinodeVPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCIPv4)(nil), (*v1alpha2.VPCIPv4)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCIPv4_To_v1alpha2_VPCIPv4(a.(*VPCIPv4), b.(*v1alpha2.VPCIPv4), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VPCIPv4)(nil), (*VPCIPv4)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VPCIPv4_To_v1alpha1_VPCIPv4(a.(*v1alpha2.VPCIPv4), b.(*VPCIPv4), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCSubnetCreateOptions)(nil), (*v1alpha2.VPCSubnetCreateOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCSubnetCreateOptions_To_v1alpha2_VPCSubnetCreateOptions(a.(*VPCSubnetCreateOptions), b.(*v1alpha2.VPCSubnetCreateOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VPCSubnetCreateOptions)(nil), (*VPCSubnetCreateOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VPCSubnetCreateOptions_To_v1alpha1_VPCSubnetCreateOptions(a.(*v1alpha2.VPCSubnetCreateOptions), b.(*VPCSubnetCreateOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*LinodeObjectStorageBucketSpec)(nil), (*v1alpha2.LinodeObjectStorageBucketSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LinodeObjectStorageBucketSpec_To_v1alpha2_LinodeObjectStorageBucketSpec(a.(*LinodeObjectStorageBucketSpec), b.(*v1alpha2.LinodeObjectStorageBucketSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*NetworkSpec)(nil), (*v1alpha2.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(a.(*NetworkSpec), b.(*v1alpha2.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.LinodeMachineSpec)(nil), (*LinodeMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeMachineSpec_To_v1alpha1_LinodeMachineSpec(a.(*v1alpha2.LinodeMachineSpec), b.(*LinodeMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.LinodeObjectStorageBucketSpec)(nil), (*LinodeObjectStorageBucketSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeObjectStorageBucketSpec_To_v1alpha1_LinodeObjectStorageBucketSpec(a.(*v1alpha2.LinodeObjectStorageBucketSpec), b.(*LinodeObjectStorageBucketSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.LinodeObjectStorageBucket)(nil), (*LinodeObjectStorageBucket)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_LinodeObjectStorageBucket_To_v1alpha1_LinodeObjectStorageBucket(a.(*v1alpha2.LinodeObjectStorageBucket), b.(*LinodeObjectStorageBucket), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(a.(*v1alpha2.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_InstanceConfigInterfaceCreateOptions_To_v1alpha2_InstanceConfigInterfaceCreateOptions(in *InstanceConfigInterfaceCreateOptions, out *v1alpha2.InstanceConfigInterfaceCreateOptions, s conversion.Scope) error {
	out.IPAMAddress = in.IPAMAddress
	out.Label = in.Label
	out.Purpose = linodego.ConfigInterfacePurpose(in.Purpose)
	out.Primary = in.Primary
	out.SubnetID = (*int)(unsafe.Pointer(in.SubnetID))
	out.IPv4 = (*v1alpha2.VPCIPv4)(unsafe.Pointer(in.IPv4))
	out.IPRanges = *(*[]string)(unsafe.Pointer(&in.IPRanges))
	return nil
}

// Convert_v1alpha1_InstanceConfigInterfaceCreateOptions_To_v1alpha2_InstanceConfigInterfaceCreateOptions is an autogenerated conversion function.
func Convert_v1alpha1_InstanceConfigInterfaceCreateOptions_To_v1alpha2_InstanceConfigInterfaceCreateOptions(in *InstanceConfigInterfaceCreateOptions, out *v1alpha2.InstanceConfigInterfaceCreateOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceConfigInterfaceCreateOptions_To_v1alpha2_InstanceConfigInterfaceCreateOptions(in, out, s)
}

func autoConvert_v1alpha2_InstanceConfigInterfaceCreateOptions_To_v1alpha1_InstanceConfigInterfaceCreateOptions(in *v1alpha2.InstanceConfigInterfaceCreateOptions, out *InstanceConfigInterfaceCreateOptions, s conversion.Scope) error {
	out.IPAMAddress = in.IPAMAddress
	out.Label = in.Label
	out.Purpose = linodego.ConfigInterfacePurpose(in.Purpose)
	out.Primary = in.Primary
	out.SubnetID = (*int)(unsafe.Pointer(in.SubnetID))
	out.IPv4 = (*VPCIPv4)(unsafe.Pointer(in.IPv4))
	out.IPRanges = *(*[]string)(unsafe.Pointer(&in.IPRanges))
	return nil
}

// Convert_v1alpha2_InstanceConfigInterfaceCreateOptions_To_v1alpha1_InstanceConfigInterfaceCreateOptions is an autogenerated conversion function.
func Convert_v1alpha2_InstanceConfigInterfaceCreateOptions_To_v1alpha1_InstanceConfigInterfaceCreateOptions(in *v1alpha2.InstanceConfigInterfaceCreateOptions, out *InstanceConfigInterfaceCreateOptions, s conversion.Scope) error {
	return autoConvert_v1alpha2_InstanceConfigInterfaceCreateOptions_To_v1alpha1_InstanceConfigInterfaceCreateOptions(in, out, s)
}

func autoConvert_v1alpha1_InstanceDisk_To_v1alpha2_InstanceDisk(in *InstanceDisk, out *v1alpha2.InstanceDisk, s conversion.Scope) error {
	out.DiskID = in.DiskID
	out.Size = in.Size
	out.Label = in.Label
	out.Filesystem = in.Filesystem
	return nil
}

// Convert_v1alpha1_InstanceDisk_To_v1alpha2_InstanceDisk is an autogenerated conversion function.
func Convert_v1alpha1_InstanceDisk_To_v1alpha2_InstanceDisk(in *InstanceDisk, out *v1alpha2.InstanceDisk, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceDisk_To_v1alpha2_InstanceDisk(in, out, s)
}

func autoConvert_v1alpha2_InstanceDisk_To_v1alpha1_InstanceDisk(in *v1alpha2.InstanceDisk, out *InstanceDisk, s conversion.Scope) error {
	out.DiskID = in.DiskID
	out.Size = in.Size
	out.Label = in.Label
	out.Filesystem = in.Filesystem
	return nil
}

// Convert_v1alpha2_InstanceDisk_To_v1alpha1_InstanceDisk is an autogenerated conversion function.
func Convert_v1alpha2_InstanceDisk_To_v1alpha1_InstanceDisk(in *v1alpha2.InstanceDisk, out *InstanceDisk, s conversion.Scope) error {
	return autoConvert_v1alpha2_InstanceDisk_To_v1alpha1_InstanceDisk(in, out, s)
}

func autoConvert_v1alpha1_InstanceMetadataOptions_To_v1alpha2_InstanceMetadataOptions(in *InstanceMetadataOptions, out *v1alpha2.InstanceMetadataOptions, s conversion.Scope) error {
	out.UserData = in.UserData
	return nil
}

// Convert_v1alpha1_InstanceMetadataOptions_To_v1alpha2_InstanceMetadataOptions is an autogenerated conversion function.
func Convert_v1alpha1_InstanceMetadataOptions_To_v1alpha2_InstanceMetadataOptions(in *InstanceMetadataOptions, out *v1alpha2.InstanceMetadataOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceMetadataOptions_To_v1alpha2_InstanceMetadataOptions(in, out, s)
}

func autoConvert_v1alpha2_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(in *v1alpha2.InstanceMetadataOptions, out *InstanceMetadataOptions, s conversion.Scope) error {
	out.UserData = in.UserData
	return nil
}

// Convert_v1alpha2_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions is an autogenerated conversion function.
func Convert_v1alpha2_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(in *v1alpha2.InstanceMetadataOptions, out *InstanceMetadataOptions, s conversion.Scope) error {
	return autoConvert_v1alpha2_InstanceMetadataOptions_To_v1alpha1_InstanceMetadataOptions(in, out, s)
}

func autoConvert_v1alpha1_LinodeCluster_To_v1alpha2_LinodeCluster(in *LinodeCluster, out *v1alpha2.LinodeCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LinodeClusterSpec_To_v1alpha2_LinodeClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LinodeClusterStatus_To_v1alpha2_LinodeClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeCluster_To_v1alpha2_LinodeCluster is an autogenerated conversion function.
func Convert_v1alpha1_LinodeCluster_To_v1alpha2_LinodeCluster(in *LinodeCluster, out *v1alpha2.LinodeCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeCluster_To_v1alpha2_LinodeCluster(in, out, s)
}

func autoConvert_v1alpha2_LinodeCluster_To_v1alpha1_LinodeCluster(in *v1alpha2.LinodeCluster, out *LinodeCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_LinodeClusterSpec_To_v1alpha1_LinodeClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_LinodeClusterStatus_To_v1alpha1_LinodeClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeCluster_To_v1alpha1_LinodeCluster is an autogenerated conversion function.
func Convert_v1alpha2_LinodeCluster_To_v1alpha1_LinodeCluster(in *v1alpha2.LinodeCluster, out *LinodeCluster, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeCluster_To_v1alpha1_LinodeCluster(in, out, s)
}

func autoConvert_v1alpha1_LinodeClusterList_To_v1alpha2_LinodeClusterList(in *LinodeClusterList, out *v1alpha2.LinodeClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.LinodeCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_LinodeCluster_To_v1alpha2_LinodeCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_LinodeClusterList_To_v1alpha2_LinodeClusterList is an autogenerated conversion function.
func Convert_v1alpha1_LinodeClusterList_To_v1alpha2_LinodeClusterList(in *LinodeClusterList, out *v1alpha2.LinodeClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeClusterList_To_v1alpha2_LinodeClusterList(in, out, s)
}

func autoConvert_v1alpha2_LinodeClusterList_To_v1alpha1_LinodeClusterList(in *v1alpha2.LinodeClusterList, out *LinodeClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinodeCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_LinodeCluster_To_v1alpha1_LinodeCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_LinodeClusterList_To_v1alpha1_LinodeClusterList is an autogenerated conversion function.
func Convert_v1alpha2_LinodeClusterList_To_v1alpha1_LinodeClusterList(in *v1alpha2.LinodeClusterList, out *LinodeClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeClusterList_To_v1alpha1_LinodeClusterList(in, out, s)
}

func autoConvert_v1alpha1_LinodeClusterSpec_To_v1alpha2_LinodeClusterSpec(in *LinodeClusterSpec, out *v1alpha2.LinodeClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if err := Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.VPCRef = (*v1.ObjectReference)(unsafe.Pointer(in.VPCRef))
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

// Convert_v1alpha1_LinodeClusterSpec_To_v1alpha2_LinodeClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_LinodeClusterSpec_To_v1alpha2_LinodeClusterSpec(in *LinodeClusterSpec, out *v1alpha2.LinodeClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeClusterSpec_To_v1alpha2_LinodeClusterSpec(in, out, s)
}

func autoConvert_v1alpha2_LinodeClusterSpec_To_v1alpha1_LinodeClusterSpec(in *v1alpha2.LinodeClusterSpec, out *LinodeClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if err := Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.VPCRef = (*v1.ObjectReference)(unsafe.Pointer(in.VPCRef))
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

// Convert_v1alpha2_LinodeClusterSpec_To_v1alpha1_LinodeClusterSpec is an autogenerated conversion function.
func Convert_v1alpha2_LinodeClusterSpec_To_v1alpha1_LinodeClusterSpec(in *v1alpha2.LinodeClusterSpec, out *LinodeClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeClusterSpec_To_v1alpha1_LinodeClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_LinodeClusterStatus_To_v1alpha2_LinodeClusterStatus(in *LinodeClusterStatus, out *v1alpha2.LinodeClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_LinodeClusterStatus_To_v1alpha2_LinodeClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_LinodeClusterStatus_To_v1alpha2_LinodeClusterStatus(in *LinodeClusterStatus, out *v1alpha2.LinodeClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeClusterStatus_To_v1alpha2_LinodeClusterStatus(in, out, s)
}

func autoConvert_v1alpha2_LinodeClusterStatus_To_v1alpha1_LinodeClusterStatus(in *v1alpha2.LinodeClusterStatus, out *LinodeClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_LinodeClusterStatus_To_v1alpha1_LinodeClusterStatus is an autogenerated conversion function.
func Convert_v1alpha2_LinodeClusterStatus_To_v1alpha1_LinodeClusterStatus(in *v1alpha2.LinodeClusterStatus, out *LinodeClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeClusterStatus_To_v1alpha1_LinodeClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_LinodeClusterTemplate_To_v1alpha2_LinodeClusterTemplate(in *LinodeClusterTemplate, out *v1alpha2.LinodeClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LinodeClusterTemplateSpec_To_v1alpha2_LinodeClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeClusterTemplate_To_v1alpha2_LinodeClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha1_LinodeClusterTemplate_To_v1alpha2_LinodeClusterTemplate(in *LinodeClusterTemplate, out *v1alpha2.LinodeClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeClusterTemplate_To_v1alpha2_LinodeClusterTemplate(in, out, s)
}

func autoConvert_v1alpha2_LinodeClusterTemplate_To_v1alpha1_LinodeClusterTemplate(in *v1alpha2.LinodeClusterTemplate, out *LinodeClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_LinodeClusterTemplateSpec_To_v1alpha1_LinodeClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeClusterTemplate_To_v1alpha1_LinodeClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha2_LinodeClusterTemplate_To_v1alpha1_LinodeClusterTemplate(in *v1alpha2.LinodeClusterTemplate, out *LinodeClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeClusterTemplate_To_v1alpha1_LinodeClusterTemplate(in, out, s)
}

func autoConvert_v1alpha1_LinodeClusterTemplateList_To_v1alpha2_LinodeClusterTemplateList(in *LinodeClusterTemplateList, out *v1alpha2.LinodeClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.LinodeClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_LinodeClusterTemplate_To_v1alpha2_LinodeClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_LinodeClusterTemplateList_To_v1alpha2_LinodeClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_LinodeClusterTemplateList_To_v1alpha2_LinodeClusterTemplateList(in *LinodeClusterTemplateList, out *v1alpha2.LinodeClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeClusterTemplateList_To_v1alpha2_LinodeClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha2_LinodeClusterTemplateList_To_v1alpha1_LinodeClusterTemplateList(in *v1alpha2.LinodeClusterTemplateList, out *LinodeClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinodeClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_LinodeClusterTemplate_To_v1alpha1_LinodeClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_LinodeClusterTemplateList_To_v1alpha1_LinodeClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_LinodeClusterTemplateList_To_v1alpha1_LinodeClusterTemplateList(in *v1alpha2.LinodeClusterTemplateList, out *LinodeClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeClusterTemplateList_To_v1alpha1_LinodeClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha1_LinodeClusterTemplateResource_To_v1alpha2_LinodeClusterTemplateResource(in *LinodeClusterTemplateResource, out *v1alpha2.LinodeClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha1_LinodeClusterSpec_To_v1alpha2_LinodeClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeClusterTemplateResource_To_v1alpha2_LinodeClusterTemplateResource is an autogenerated conversion function.
func Convert_v1alpha1_LinodeClusterTemplateResource_To_v1alpha2_LinodeClusterTemplateResource(in *LinodeClusterTemplateResource, out *v1alpha2.LinodeClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeClusterTemplateResource_To_v1alpha2_LinodeClusterTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_LinodeClusterTemplateResource_To_v1alpha1_LinodeClusterTemplateResource(in *v1alpha2.LinodeClusterTemplateResource, out *LinodeClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha2_LinodeClusterSpec_To_v1alpha1_LinodeClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeClusterTemplateResource_To_v1alpha1_LinodeClusterTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_LinodeClusterTemplateResource_To_v1alpha1_LinodeClusterTemplateResource(in *v1alpha2.LinodeClusterTemplateResource, out *LinodeClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeClusterTemplateResource_To_v1alpha1_LinodeClusterTemplateResource(in, out, s)
}

func autoConvert_v1alpha1_LinodeClusterTemplateSpec_To_v1alpha2_LinodeClusterTemplateSpec(in *LinodeClusterTemplateSpec, out *v1alpha2.LinodeClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LinodeClusterTemplateResource_To_v1alpha2_LinodeClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeClusterTemplateSpec_To_v1alpha2_LinodeClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_LinodeClusterTemplateSpec_To_v1alpha2_LinodeClusterTemplateSpec(in *LinodeClusterTemplateSpec, out *v1alpha2.LinodeClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeClusterTemplateSpec_To_v1alpha2_LinodeClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_LinodeClusterTemplateSpec_To_v1alpha1_LinodeClusterTemplateSpec(in *v1alpha2.LinodeClusterTemplateSpec, out *LinodeClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_LinodeClusterTemplateResource_To_v1alpha1_LinodeClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeClusterTemplateSpec_To_v1alpha1_LinodeClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_LinodeClusterTemplateSpec_To_v1alpha1_LinodeClusterTemplateSpec(in *v1alpha2.LinodeClusterTemplateSpec, out *LinodeClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeClusterTemplateSpec_To_v1alpha1_LinodeClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_LinodeMachine_To_v1alpha2_LinodeMachine(in *LinodeMachine, out *v1alpha2.LinodeMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LinodeMachineSpec_To_v1alpha2_LinodeMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LinodeMachineStatus_To_v1alpha2_LinodeMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeMachine_To_v1alpha2_LinodeMachine is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachine_To_v1alpha2_LinodeMachine(in *LinodeMachine, out *v1alpha2.LinodeMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachine_To_v1alpha2_LinodeMachine(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachine_To_v1alpha1_LinodeMachine(in *v1alpha2.LinodeMachine, out *LinodeMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_LinodeMachineSpec_To_v1alpha1_LinodeMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_LinodeMachineStatus_To_v1alpha1_LinodeMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeMachine_To_v1alpha1_LinodeMachine is an autogenerated conversion function.
func Convert_v1alpha2_LinodeMachine_To_v1alpha1_LinodeMachine(in *v1alpha2.LinodeMachine, out *LinodeMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeMachine_To_v1alpha1_LinodeMachine(in, out, s)
}

func autoConvert_v1alpha1_LinodeMachineList_To_v1alpha2_LinodeMachineList(in *LinodeMachineList, out *v1alpha2.LinodeMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.LinodeMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_LinodeMachine_To_v1alpha2_LinodeMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_LinodeMachineList_To_v1alpha2_LinodeMachineList is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachineList_To_v1alpha2_LinodeMachineList(in *LinodeMachineList, out *v1alpha2.LinodeMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachineList_To_v1alpha2_LinodeMachineList(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachineList_To_v1alpha1_LinodeMachineList(in *v1alpha2.LinodeMachineList, out *LinodeMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinodeMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_LinodeMachine_To_v1alpha1_LinodeMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_LinodeMachineList_To_v1alpha1_LinodeMachineList is an autogenerated conversion function.
func Convert_v1alpha2_LinodeMachineList_To_v1alpha1_LinodeMachineList(in *v1alpha2.LinodeMachineList, out *LinodeMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeMachineList_To_v1alpha1_LinodeMachineList(in, out, s)
}

func autoConvert_v1alpha1_LinodeMachineSpec_To_v1alpha2_LinodeMachineSpec(in *LinodeMachineSpec, out *v1alpha2.LinodeMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.InstanceID = (*int)(unsafe.Pointer(in.InstanceID))
	out.Region = in.Region
	out.Type = in.Type
	out.Group = in.Group
	out.RootPass = in.RootPass
	out.AuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.AuthorizedKeys))
	out.AuthorizedUsers = *(*[]string)(unsafe.Pointer(&in.AuthorizedUsers))
	out.BackupID = in.BackupID
	out.Image = in.Image
	out.Interfaces = *(*[]v1alpha2.InstanceConfigInterfaceCreateOptions)(unsafe.Pointer(&in.Interfaces))
	out.BackupsEnabled = in.BackupsEnabled
	out.PrivateIP = (*bool)(unsafe.Pointer(in.PrivateIP))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.FirewallID = in.FirewallID
	out.OSDisk = (*v1alpha2.InstanceDisk)(unsafe.Pointer(in.OSDisk))
	out.DataDisks = *(*map[string]*v1alpha2.InstanceDisk)(unsafe.Pointer(&in.DataDisks))
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

// Convert_v1alpha1_LinodeMachineSpec_To_v1alpha2_LinodeMachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachineSpec_To_v1alpha2_LinodeMachineSpec(in *LinodeMachineSpec, out *v1alpha2.LinodeMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachineSpec_To_v1alpha2_LinodeMachineSpec(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachineSpec_To_v1alpha1_LinodeMachineSpec(in *v1alpha2.LinodeMachineSpec, out *LinodeMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.InstanceID = (*int)(unsafe.Pointer(in.InstanceID))
	out.Region = in.Region
	out.Type = in.Type
	out.Group = in.Group
	out.RootPass = in.RootPass
	out.AuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.AuthorizedKeys))
	out.AuthorizedUsers = *(*[]string)(unsafe.Pointer(&in.AuthorizedUsers))
	out.BackupID = in.BackupID
	out.Image = in.Image
	out.Interfaces = *(*[]InstanceConfigInterfaceCreateOptions)(unsafe.Pointer(&in.Interfaces))
	out.BackupsEnabled = in.BackupsEnabled
	out.PrivateIP = (*bool)(unsafe.Pointer(in.PrivateIP))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	out.FirewallID = in.FirewallID
	out.OSDisk = (*InstanceDisk)(unsafe.Pointer(in.OSDisk))
	out.DataDisks = *(*map[string]*InstanceDisk)(unsafe.Pointer(&in.DataDisks))
	// WARNING: in.DiskEncryption requires manual conversion: does not exist in peer-type
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	// WARNING: in.Configuration requires manual conversion: does not exist in peer-type
	// WARNING: in.PlacementGroupRef requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_LinodeMachineStatus_To_v1alpha2_LinodeMachineStatus(in *LinodeMachineStatus, out *v1alpha2.LinodeMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceState = (*linodego.InstanceStatus)(unsafe.Pointer(in.InstanceState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_LinodeMachineStatus_To_v1alpha2_LinodeMachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachineStatus_To_v1alpha2_LinodeMachineStatus(in *LinodeMachineStatus, out *v1alpha2.LinodeMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachineStatus_To_v1alpha2_LinodeMachineStatus(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachineStatus_To_v1alpha1_LinodeMachineStatus(in *v1alpha2.LinodeMachineStatus, out *LinodeMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceState = (*linodego.InstanceStatus)(unsafe.Pointer(in.InstanceState))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_LinodeMachineStatus_To_v1alpha1_LinodeMachineStatus is an autogenerated conversion function.
func Convert_v1alpha2_LinodeMachineStatus_To_v1alpha1_LinodeMachineStatus(in *v1alpha2.LinodeMachineStatus, out *LinodeMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeMachineStatus_To_v1alpha1_LinodeMachineStatus(in, out, s)
}

func autoConvert_v1alpha1_LinodeMachineTemplate_To_v1alpha2_LinodeMachineTemplate(in *LinodeMachineTemplate, out *v1alpha2.LinodeMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LinodeMachineTemplateSpec_To_v1alpha2_LinodeMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeMachineTemplate_To_v1alpha2_LinodeMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachineTemplate_To_v1alpha2_LinodeMachineTemplate(in *LinodeMachineTemplate, out *v1alpha2.LinodeMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachineTemplate_To_v1alpha2_LinodeMachineTemplate(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachineTemplate_To_v1alpha1_LinodeMachineTemplate(in *v1alpha2.LinodeMachineTemplate, out *LinodeMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_LinodeMachineTemplateSpec_To_v1alpha1_LinodeMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeMachineTemplate_To_v1alpha1_LinodeMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha2_LinodeMachineTemplate_To_v1alpha1_LinodeMachineTemplate(in *v1alpha2.LinodeMachineTemplate, out *LinodeMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeMachineTemplate_To_v1alpha1_LinodeMachineTemplate(in, out, s)
}

func autoConvert_v1alpha1_LinodeMachineTemplateList_To_v1alpha2_LinodeMachineTemplateList(in *LinodeMachineTemplateList, out *v1alpha2.LinodeMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.LinodeMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_LinodeMachineTemplate_To_v1alpha2_LinodeMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_LinodeMachineTemplateList_To_v1alpha2_LinodeMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachineTemplateList_To_v1alpha2_LinodeMachineTemplateList(in *LinodeMachineTemplateList, out *v1alpha2.LinodeMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachineTemplateList_To_v1alpha2_LinodeMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachineTemplateList_To_v1alpha1_LinodeMachineTemplateList(in *v1alpha2.LinodeMachineTemplateList, out *LinodeMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinodeMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_LinodeMachineTemplate_To_v1alpha1_LinodeMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_LinodeMachineTemplateList_To_v1alpha1_LinodeMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_LinodeMachineTemplateList_To_v1alpha1_LinodeMachineTemplateList(in *v1alpha2.LinodeMachineTemplateList, out *LinodeMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeMachineTemplateList_To_v1alpha1_LinodeMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha1_LinodeMachineTemplateResource_To_v1alpha2_LinodeMachineTemplateResource(in *LinodeMachineTemplateResource, out *v1alpha2.LinodeMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha1_LinodeMachineSpec_To_v1alpha2_LinodeMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeMachineTemplateResource_To_v1alpha2_LinodeMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachineTemplateResource_To_v1alpha2_LinodeMachineTemplateResource(in *LinodeMachineTemplateResource, out *v1alpha2.LinodeMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachineTemplateResource_To_v1alpha2_LinodeMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachineTemplateResource_To_v1alpha1_LinodeMachineTemplateResource(in *v1alpha2.LinodeMachineTemplateResource, out *LinodeMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha2_LinodeMachineSpec_To_v1alpha1_LinodeMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeMachineTemplateResource_To_v1alpha1_LinodeMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_LinodeMachineTemplateResource_To_v1alpha1_LinodeMachineTemplateResource(in *v1alpha2.LinodeMachineTemplateResource, out *LinodeMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeMachineTemplateResource_To_v1alpha1_LinodeMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha1_LinodeMachineTemplateSpec_To_v1alpha2_LinodeMachineTemplateSpec(in *LinodeMachineTemplateSpec, out *v1alpha2.LinodeMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_LinodeMachineTemplateResource_To_v1alpha2_LinodeMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeMachineTemplateSpec_To_v1alpha2_LinodeMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_LinodeMachineTemplateSpec_To_v1alpha2_LinodeMachineTemplateSpec(in *LinodeMachineTemplateSpec, out *v1alpha2.LinodeMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeMachineTemplateSpec_To_v1alpha2_LinodeMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_LinodeMachineTemplateSpec_To_v1alpha1_LinodeMachineTemplateSpec(in *v1alpha2.LinodeMachineTemplateSpec, out *LinodeMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_LinodeMachineTemplateResource_To_v1alpha1_LinodeMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeMachineTemplateSpec_To_v1alpha1_LinodeMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_LinodeMachineTemplateSpec_To_v1alpha1_LinodeMachineTemplateSpec(in *v1alpha2.LinodeMachineTemplateSpec, out *LinodeMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeMachineTemplateSpec_To_v1alpha1_LinodeMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_LinodeObjectStorageBucket_To_v1alpha2_LinodeObjectStorageBucket(in *LinodeObjectStorageBucket, out *v1alpha2.LinodeObjectStorageBucket, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LinodeObjectStorageBucketSpec_To_v1alpha2_LinodeObjectStorageBucketSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LinodeObjectStorageBucketStatus_To_v1alpha2_LinodeObjectStorageBucketStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeObjectStorageBucket_To_v1alpha2_LinodeObjectStorageBucket is an autogenerated conversion function.
func Convert_v1alpha1_LinodeObjectStorageBucket_To_v1alpha2_LinodeObjectStorageBucket(in *LinodeObjectStorageBucket, out *v1alpha2.LinodeObjectStorageBucket, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeObjectStorageBucket_To_v1alpha2_LinodeObjectStorageBucket(in, out, s)
}

func autoConvert_v1alpha2_LinodeObjectStorageBucket_To_v1alpha1_LinodeObjectStorageBucket(in *v1alpha2.LinodeObjectStorageBucket, out *LinodeObjectStorageBucket, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_LinodeObjectStorageBucketSpec_To_v1alpha1_LinodeObjectStorageBucketSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_LinodeObjectStorageBucketStatus_To_v1alpha1_LinodeObjectStorageBucketStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_LinodeObjectStorageBucketList_To_v1alpha2_LinodeObjectStorageBucketList(in *LinodeObjectStorageBucketList, out *v1alpha2.LinodeObjectStorageBucketList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.LinodeObjectStorageBucket, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_LinodeObjectStorageBucket_To_v1alpha2_LinodeObjectStorageBucket(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_LinodeObjectStorageBucketList_To_v1alpha2_LinodeObjectStorageBucketList is an autogenerated conversion function.
func Convert_v1alpha1_LinodeObjectStorageBucketList_To_v1alpha2_LinodeObjectStorageBucketList(in *LinodeObjectStorageBucketList, out *v1alpha2.LinodeObjectStorageBucketList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeObjectStorageBucketList_To_v1alpha2_LinodeObjectStorageBucketList(in, out, s)
}

func autoConvert_v1alpha2_LinodeObjectStorageBucketList_To_v1alpha1_LinodeObjectStorageBucketList(in *v1alpha2.LinodeObjectStorageBucketList, out *LinodeObjectStorageBucketList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinodeObjectStorageBucket, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_LinodeObjectStorageBucket_To_v1alpha1_LinodeObjectStorageBucket(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_LinodeObjectStorageBucketList_To_v1alpha1_LinodeObjectStorageBucketList is an autogenerated conversion function.
func Convert_v1alpha2_LinodeObjectStorageBucketList_To_v1alpha1_LinodeObjectStorageBucketList(in *v1alpha2.LinodeObjectStorageBucketList, out *LinodeObjectStorageBucketList, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeObjectStorageBucketList_To_v1alpha1_LinodeObjectStorageBucketList(in, out, s)
}

func autoConvert_v1alpha1_LinodeObjectStorageBucketSpec_To_v1alpha2_LinodeObjectStorageBucketSpec(in *LinodeObjectStorageBucketSpec, out *v1alpha2.LinodeObjectStorageBucketSpec, s conversion.Scope) error {
	// WARNING: in.Cluster requires manual conversion: does not exist in peer-type
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	out.KeyGeneration = (*int)(unsafe.Pointer(in.KeyGeneration))
	out.SecretType = in.SecretType
	return nil
}

func autoConvert_v1alpha2_LinodeObjectStorageBucketSpec_To_v1alpha1_LinodeObjectStorageBucketSpec(in *v1alpha2.LinodeObjectStorageBucketSpec, out *LinodeObjectStorageBucketSpec, s conversion.Scope) error {
	// WARNING: in.Region requires manual conversion: does not exist in peer-type
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	out.KeyGeneration = (*int)(unsafe.Pointer(in.KeyGeneration))
	out.SecretType = in.SecretType
	return nil
}

func autoConvert_v1alpha1_LinodeObjectStorageBucketStatus_To_v1alpha2_LinodeObjectStorageBucketStatus(in *LinodeObjectStorageBucketStatus, out *v1alpha2.LinodeObjectStorageBucketStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.Hostname = (*string)(unsafe.Pointer(in.Hostname))
	out.CreationTime = (*metav1.Time)(unsafe.Pointer(in.CreationTime))
	out.LastKeyGeneration = (*int)(unsafe.Pointer(in.LastKeyGeneration))
	out.KeySecretName = (*string)(unsafe.Pointer(in.KeySecretName))
	out.AccessKeyRefs = *(*[]int)(unsafe.Pointer(&in.AccessKeyRefs))
	return nil
}

// Convert_v1alpha1_LinodeObjectStorageBucketStatus_To_v1alpha2_LinodeObjectStorageBucketStatus is an autogenerated conversion function.
func Convert_v1alpha1_LinodeObjectStorageBucketStatus_To_v1alpha2_LinodeObjectStorageBucketStatus(in *LinodeObjectStorageBucketStatus, out *v1alpha2.LinodeObjectStorageBucketStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeObjectStorageBucketStatus_To_v1alpha2_LinodeObjectStorageBucketStatus(in, out, s)
}

func autoConvert_v1alpha2_LinodeObjectStorageBucketStatus_To_v1alpha1_LinodeObjectStorageBucketStatus(in *v1alpha2.LinodeObjectStorageBucketStatus, out *LinodeObjectStorageBucketStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.Hostname = (*string)(unsafe.Pointer(in.Hostname))
	out.CreationTime = (*metav1.Time)(unsafe.Pointer(in.CreationTime))
	out.LastKeyGeneration = (*int)(unsafe.Pointer(in.LastKeyGeneration))
	out.KeySecretName = (*string)(unsafe.Pointer(in.KeySecretName))
	out.AccessKeyRefs = *(*[]int)(unsafe.Pointer(&in.AccessKeyRefs))
	return nil
}

// Convert_v1alpha2_LinodeObjectStorageBucketStatus_To_v1alpha1_LinodeObjectStorageBucketStatus is an autogenerated conversion function.
func Convert_v1alpha2_LinodeObjectStorageBucketStatus_To_v1alpha1_LinodeObjectStorageBucketStatus(in *v1alpha2.LinodeObjectStorageBucketStatus, out *LinodeObjectStorageBucketStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeObjectStorageBucketStatus_To_v1alpha1_LinodeObjectStorageBucketStatus(in, out, s)
}

func autoConvert_v1alpha1_LinodeVPC_To_v1alpha2_LinodeVPC(in *LinodeVPC, out *v1alpha2.LinodeVPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LinodeVPCSpec_To_v1alpha2_LinodeVPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LinodeVPCStatus_To_v1alpha2_LinodeVPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LinodeVPC_To_v1alpha2_LinodeVPC is an autogenerated conversion function.
func Convert_v1alpha1_LinodeVPC_To_v1alpha2_LinodeVPC(in *LinodeVPC, out *v1alpha2.LinodeVPC, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeVPC_To_v1alpha2_LinodeVPC(in, out, s)
}

func autoConvert_v1alpha2_LinodeVPC_To_v1alpha1_LinodeVPC(in *v1alpha2.LinodeVPC, out *LinodeVPC, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_LinodeVPCSpec_To_v1alpha1_LinodeVPCSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_LinodeVPCStatus_To_v1alpha1_LinodeVPCStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_LinodeVPC_To_v1alpha1_LinodeVPC is an autogenerated conversion function.
func Convert_v1alpha2_LinodeVPC_To_v1alpha1_LinodeVPC(in *v1alpha2.LinodeVPC, out *LinodeVPC, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeVPC_To_v1alpha1_LinodeVPC(in, out, s)
}

func autoConvert_v1alpha1_LinodeVPCList_To_v1alpha2_LinodeVPCList(in *LinodeVPCList, out *v1alpha2.LinodeVPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha2.LinodeVPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_LinodeVPCList_To_v1alpha2_LinodeVPCList is an autogenerated conversion function.
func Convert_v1alpha1_LinodeVPCList_To_v1alpha2_LinodeVPCList(in *LinodeVPCList, out *v1alpha2.LinodeVPCList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeVPCList_To_v1alpha2_LinodeVPCList(in, out, s)
}

func autoConvert_v1alpha2_LinodeVPCList_To_v1alpha1_LinodeVPCList(in *v1alpha2.LinodeVPCList, out *LinodeVPCList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]LinodeVPC)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_LinodeVPCList_To_v1alpha1_LinodeVPCList is an autogenerated conversion function.
func Convert_v1alpha2_LinodeVPCList_To_v1alpha1_LinodeVPCList(in *v1alpha2.LinodeVPCList, out *LinodeVPCList, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeVPCList_To_v1alpha1_LinodeVPCList(in, out, s)
}

func autoConvert_v1alpha1_LinodeVPCSpec_To_v1alpha2_LinodeVPCSpec(in *LinodeVPCSpec, out *v1alpha2.LinodeVPCSpec, s conversion.Scope) error {
	out.VPCID = (*int)(unsafe.Pointer(in.VPCID))
	out.Description = in.Description
	out.Region = in.Region
	out.Subnets = *(*[]v1alpha2.VPCSubnetCreateOptions)(unsafe.Pointer(&in.Subnets))
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

// Convert_v1alpha1_LinodeVPCSpec_To_v1alpha2_LinodeVPCSpec is an autogenerated conversion function.
func Convert_v1alpha1_LinodeVPCSpec_To_v1alpha2_LinodeVPCSpec(in *LinodeVPCSpec, out *v1alpha2.LinodeVPCSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeVPCSpec_To_v1alpha2_LinodeVPCSpec(in, out, s)
}

func autoConvert_v1alpha2_LinodeVPCSpec_To_v1alpha1_LinodeVPCSpec(in *v1alpha2.LinodeVPCSpec, out *LinodeVPCSpec, s conversion.Scope) error {
	out.VPCID = (*int)(unsafe.Pointer(in.VPCID))
	out.Description = in.Description
	out.Region = in.Region
	out.Subnets = *(*[]VPCSubnetCreateOptions)(unsafe.Pointer(&in.Subnets))
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

// Convert_v1alpha2_LinodeVPCSpec_To_v1alpha1_LinodeVPCSpec is an autogenerated conversion function.
func Convert_v1alpha2_LinodeVPCSpec_To_v1alpha1_LinodeVPCSpec(in *v1alpha2.LinodeVPCSpec, out *LinodeVPCSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeVPCSpec_To_v1alpha1_LinodeVPCSpec(in, out, s)
}

func autoConvert_v1alpha1_LinodeVPCStatus_To_v1alpha2_LinodeVPCStatus(in *LinodeVPCStatus, out *v1alpha2.LinodeVPCStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureReason = (*v1alpha2.VPCStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_LinodeVPCStatus_To_v1alpha2_LinodeVPCStatus is an autogenerated conversion function.
func Convert_v1alpha1_LinodeVPCStatus_To_v1alpha2_LinodeVPCStatus(in *LinodeVPCStatus, out *v1alpha2.LinodeVPCStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LinodeVPCStatus_To_v1alpha2_LinodeVPCStatus(in, out, s)
}

func autoConvert_v1alpha2_LinodeVPCStatus_To_v1alpha1_LinodeVPCStatus(in *v1alpha2.LinodeVPCStatus, out *LinodeVPCStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.FailureReason = (*VPCStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_LinodeVPCStatus_To_v1alpha1_LinodeVPCStatus is an autogenerated conversion function.
func Convert_v1alpha2_LinodeVPCStatus_To_v1alpha1_LinodeVPCStatus(in *v1alpha2.LinodeVPCStatus, out *LinodeVPCStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_LinodeVPCStatus_To_v1alpha1_LinodeVPCStatus(in, out, s)
}

func autoConvert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in *NetworkSpec, out *v1alpha2.NetworkSpec, s conversion.Scope) error {
	out.LoadBalancerType = in.LoadBalancerType
	// WARNING: in.LoadBalancerPort requires manual conversion: does not exist in peer-type
	out.NodeBalancerID = (*int)(unsafe.Pointer(in.NodeBalancerID))
	// WARNING: in.NodeBalancerConfigID requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in *v1alpha2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	out.LoadBalancerType = in.LoadBalancerType
	// WARNING: in.DNSProvider requires manual conversion: does not exist in peer-type
	// WARNING: in.DNSRootDomain requires manual conversion: does not exist in peer-type
	// WARNING: in.DNSUniqueIdentifier requires manual conversion: does not exist in peer-type
	// WARNING: in.DNSTTLSec requires manual conversion: does not exist in peer-type
	// WARNING: in.DNSEndpointOverride requires manual conversion: does not exist in peer-type
	// WARNING: in.ApiserverLoadBalancerPort requires manual conversion: does not exist in peer-type
	out.NodeBalancerID = (*int)(unsafe.Pointer(in.NodeBalancerID))
	// WARNING: in.ApiserverNodeBalancerConfigID requires manual conversion: does not exist in peer-type
	// WARNING: in.AdditionalPorts requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_VPCIPv4_To_v1alpha2_VPCIPv4(in *VPCIPv4, out *v1alpha2.VPCIPv4, s conversion.Scope) error {
	out.VPC = in.VPC
	out.NAT1To1 = in.NAT1To1
	return nil
}

// Convert_v1alpha1_VPCIPv4_To_v1alpha2_VPCIPv4 is an autogenerated conversion function.
func Convert_v1alpha1_VPCIPv4_To_v1alpha2_VPCIPv4(in *VPCIPv4, out *v1alpha2.VPCIPv4, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCIPv4_To_v1alpha2_VPCIPv4(in, out, s)
}

func autoConvert_v1alpha2_VPCIPv4_To_v1alpha1_VPCIPv4(in *v1alpha2.VPCIPv4, out *VPCIPv4, s conversion.Scope) error {
	out.VPC = in.VPC
	out.NAT1To1 = in.NAT1To1
	return nil
}

// Convert_v1alpha2_VPCIPv4_To_v1alpha1_VPCIPv4 is an autogenerated conversion function.
func Convert_v1alpha2_VPCIPv4_To_v1alpha1_VPCIPv4(in *v1alpha2.VPCIPv4, out *VPCIPv4, s conversion.Scope) error {
	return autoConvert_v1alpha2_VPCIPv4_To_v1alpha1_VPCIPv4(in, out, s)
}

func autoConvert_v1alpha1_VPCSubnetCreateOptions_To_v1alpha2_VPCSubnetCreateOptions(in *VPCSubnetCreateOptions, out *v1alpha2.VPCSubnetCreateOptions, s conversion.Scope) error {
	out.Label = in.Label
	out.IPv4 = in.IPv4
	return nil
}

// Convert_v1alpha1_VPCSubnetCreateOptions_To_v1alpha2_VPCSubnetCreateOptions is an autogenerated conversion function.
func Convert_v1alpha1_VPCSubnetCreateOptions_To_v1alpha2_VPCSubnetCreateOptions(in *VPCSubnetCreateOptions, out *v1alpha2.VPCSubnetCreateOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCSubnetCreateOptions_To_v1alpha2_VPCSubnetCreateOptions(in, out, s)
}

func autoConvert_v1alpha2_VPCSubnetCreateOptions_To_v1alpha1_VPCSubnetCreateOptions(in *v1alpha2.VPCSubnetCreateOptions, out *VPCSubnetCreateOptions, s conversion.Scope) error {
	out.Label = in.Label
	out.IPv4 = in.IPv4
	return nil
}

// Convert_v1alpha2_VPCSubnetCreateOptions_To_v1alpha1_VPCSubnetCreateOptions is an autogenerated conversion function.
func Convert_v1alpha2_VPCSubnetCreateOptions_To_v1alpha1_VPCSubnetCreateOptions(in *v1alpha2.VPCSubnetCreateOptions, out *VPCSubnetCreateOptions, s conversion.Scope) error {
	return autoConvert_v1alpha2_VPCSubnetCreateOptions_To_v1alpha1_VPCSubnetCreateOptions(in, out, s)
}
