//go:build !ignore_autogenerated

/*
Copyright 2023 Akamai Technologies, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/linode/linodego"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfig) DeepCopyInto(out *DNSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfig.
func (in *DNSConfig) DeepCopy() *DNSConfig {
	if in == nil {
		return nil
	}
	out := new(DNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDisks) DeepCopyInto(out *DataDisks) {
	*out = *in
	if in.SDB != nil {
		in, out := &in.SDB, &out.SDB
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.SDC != nil {
		in, out := &in.SDC, &out.SDC
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.SDD != nil {
		in, out := &in.SDD, &out.SDD
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.SDE != nil {
		in, out := &in.SDE, &out.SDE
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.SDF != nil {
		in, out := &in.SDF, &out.SDF
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.SDG != nil {
		in, out := &in.SDG, &out.SDG
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.SDH != nil {
		in, out := &in.SDH, &out.SDH
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDisks.
func (in *DataDisks) DeepCopy() *DataDisks {
	if in == nil {
		return nil
	}
	out := new(DataDisks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv6CreateOptions) DeepCopyInto(out *IPv6CreateOptions) {
	*out = *in
	if in.EnableSLAAC != nil {
		in, out := &in.EnableSLAAC, &out.EnableSLAAC
		*out = new(bool)
		**out = **in
	}
	if in.EnableRanges != nil {
		in, out := &in.EnableRanges, &out.EnableRanges
		*out = new(bool)
		**out = **in
	}
	if in.IsPublicIPv6 != nil {
		in, out := &in.IsPublicIPv6, &out.IsPublicIPv6
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv6CreateOptions.
func (in *IPv6CreateOptions) DeepCopy() *IPv6CreateOptions {
	if in == nil {
		return nil
	}
	out := new(IPv6CreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceConfigInterfaceCreateOptions) DeepCopyInto(out *InstanceConfigInterfaceCreateOptions) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(int)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(VPCIPv4)
		**out = **in
	}
	if in.IPRanges != nil {
		in, out := &in.IPRanges, &out.IPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceConfigInterfaceCreateOptions.
func (in *InstanceConfigInterfaceCreateOptions) DeepCopy() *InstanceConfigInterfaceCreateOptions {
	if in == nil {
		return nil
	}
	out := new(InstanceConfigInterfaceCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceDisk) DeepCopyInto(out *InstanceDisk) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceDisk.
func (in *InstanceDisk) DeepCopy() *InstanceDisk {
	if in == nil {
		return nil
	}
	out := new(InstanceDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMetadataOptions) DeepCopyInto(out *InstanceMetadataOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMetadataOptions.
func (in *InstanceMetadataOptions) DeepCopy() *InstanceMetadataOptions {
	if in == nil {
		return nil
	}
	out := new(InstanceMetadataOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceDefaultRoute) DeepCopyInto(out *InterfaceDefaultRoute) {
	*out = *in
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(bool)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceDefaultRoute.
func (in *InterfaceDefaultRoute) DeepCopy() *InterfaceDefaultRoute {
	if in == nil {
		return nil
	}
	out := new(InterfaceDefaultRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeCluster) DeepCopyInto(out *LinodeCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeCluster.
func (in *LinodeCluster) DeepCopy() *LinodeCluster {
	if in == nil {
		return nil
	}
	out := new(LinodeCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinodeCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeClusterList) DeepCopyInto(out *LinodeClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinodeCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeClusterList.
func (in *LinodeClusterList) DeepCopy() *LinodeClusterList {
	if in == nil {
		return nil
	}
	out := new(LinodeClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinodeClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeClusterSpec) DeepCopyInto(out *LinodeClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	in.Network.DeepCopyInto(&out.Network)
	if in.VPCRef != nil {
		in, out := &in.VPCRef, &out.VPCRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(int)
		**out = **in
	}
	if in.NodeBalancerFirewallRef != nil {
		in, out := &in.NodeBalancerFirewallRef, &out.NodeBalancerFirewallRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ObjectStore != nil {
		in, out := &in.ObjectStore, &out.ObjectStore
		*out = new(ObjectStore)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeClusterSpec.
func (in *LinodeClusterSpec) DeepCopy() *LinodeClusterSpec {
	if in == nil {
		return nil
	}
	out := new(LinodeClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeClusterStatus) DeepCopyInto(out *LinodeClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeClusterStatus.
func (in *LinodeClusterStatus) DeepCopy() *LinodeClusterStatus {
	if in == nil {
		return nil
	}
	out := new(LinodeClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeInterfaceCreateOptions) DeepCopyInto(out *LinodeInterfaceCreateOptions) {
	*out = *in
	if in.FirewallID != nil {
		in, out := &in.FirewallID, &out.FirewallID
		*out = new(int)
		**out = **in
	}
	if in.DefaultRoute != nil {
		in, out := &in.DefaultRoute, &out.DefaultRoute
		*out = new(InterfaceDefaultRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(PublicInterfaceCreateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.VPC != nil {
		in, out := &in.VPC, &out.VPC
		*out = new(VPCInterfaceCreateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = new(VLANInterface)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeInterfaceCreateOptions.
func (in *LinodeInterfaceCreateOptions) DeepCopy() *LinodeInterfaceCreateOptions {
	if in == nil {
		return nil
	}
	out := new(LinodeInterfaceCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeMachine) DeepCopyInto(out *LinodeMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeMachine.
func (in *LinodeMachine) DeepCopy() *LinodeMachine {
	if in == nil {
		return nil
	}
	out := new(LinodeMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinodeMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeMachineList) DeepCopyInto(out *LinodeMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinodeMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeMachineList.
func (in *LinodeMachineList) DeepCopy() *LinodeMachineList {
	if in == nil {
		return nil
	}
	out := new(LinodeMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinodeMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeMachineSpec) DeepCopyInto(out *LinodeMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(int)
		**out = **in
	}
	if in.OSDisk != nil {
		in, out := &in.OSDisk, &out.OSDisk
		*out = new(InstanceDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.DataDisks != nil {
		in, out := &in.DataDisks, &out.DataDisks
		*out = new(DataDisks)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.PlacementGroupRef != nil {
		in, out := &in.PlacementGroupRef, &out.PlacementGroupRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.FirewallRef != nil {
		in, out := &in.FirewallRef, &out.FirewallRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.VPCRef != nil {
		in, out := &in.VPCRef, &out.VPCRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(int)
		**out = **in
	}
	if in.IPv6Options != nil {
		in, out := &in.IPv6Options, &out.IPv6Options
		*out = new(IPv6CreateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizedKeys != nil {
		in, out := &in.AuthorizedKeys, &out.AuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedUsers != nil {
		in, out := &in.AuthorizedUsers, &out.AuthorizedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrivateIP != nil {
		in, out := &in.PrivateIP, &out.PrivateIP
		*out = new(bool)
		**out = **in
	}
	if in.NetworkHelper != nil {
		in, out := &in.NetworkHelper, &out.NetworkHelper
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]InstanceConfigInterfaceCreateOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LinodeInterfaces != nil {
		in, out := &in.LinodeInterfaces, &out.LinodeInterfaces
		*out = make([]LinodeInterfaceCreateOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeMachineSpec.
func (in *LinodeMachineSpec) DeepCopy() *LinodeMachineSpec {
	if in == nil {
		return nil
	}
	out := new(LinodeMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeMachineStatus) DeepCopyInto(out *LinodeMachineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]v1beta2.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.InstanceState != nil {
		in, out := &in.InstanceState, &out.InstanceState
		*out = new(linodego.InstanceStatus)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeMachineStatus.
func (in *LinodeMachineStatus) DeepCopy() *LinodeMachineStatus {
	if in == nil {
		return nil
	}
	out := new(LinodeMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinodeNBPortConfig) DeepCopyInto(out *LinodeNBPortConfig) {
	*out = *in
	if in.NodeBalancerConfigID != nil {
		in, out := &in.NodeBalancerConfigID, &out.NodeBalancerConfigID
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinodeNBPortConfig.
func (in *LinodeNBPortConfig) DeepCopy() *LinodeNBPortConfig {
	if in == nil {
		return nil
	}
	out := new(LinodeNBPortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(DNSConfig)
		**out = **in
	}
	if in.NodeBalancerConfig != nil {
		in, out := &in.NodeBalancerConfig, &out.NodeBalancerConfig
		*out = new(NodeBalancerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeBalancerConfig) DeepCopyInto(out *NodeBalancerConfig) {
	*out = *in
	if in.NodeBalancerID != nil {
		in, out := &in.NodeBalancerID, &out.NodeBalancerID
		*out = new(int)
		**out = **in
	}
	if in.NodeBalancerFirewallID != nil {
		in, out := &in.NodeBalancerFirewallID, &out.NodeBalancerFirewallID
		*out = new(int)
		**out = **in
	}
	if in.ApiserverNodeBalancerConfigID != nil {
		in, out := &in.ApiserverNodeBalancerConfigID, &out.ApiserverNodeBalancerConfigID
		*out = new(int)
		**out = **in
	}
	if in.AdditionalPorts != nil {
		in, out := &in.AdditionalPorts, &out.AdditionalPorts
		*out = make([]LinodeNBPortConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeBalancerConfig.
func (in *NodeBalancerConfig) DeepCopy() *NodeBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(NodeBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStore) DeepCopyInto(out *ObjectStore) {
	*out = *in
	if in.PresignedURLDuration != nil {
		in, out := &in.PresignedURLDuration, &out.PresignedURLDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	out.CredentialsRef = in.CredentialsRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStore.
func (in *ObjectStore) DeepCopy() *ObjectStore {
	if in == nil {
		return nil
	}
	out := new(ObjectStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicInterfaceCreateOptions) DeepCopyInto(out *PublicInterfaceCreateOptions) {
	*out = *in
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(PublicInterfaceIPv4CreateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(PublicInterfaceIPv6CreateOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicInterfaceCreateOptions.
func (in *PublicInterfaceCreateOptions) DeepCopy() *PublicInterfaceCreateOptions {
	if in == nil {
		return nil
	}
	out := new(PublicInterfaceCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicInterfaceIPv4AddressCreateOptions) DeepCopyInto(out *PublicInterfaceIPv4AddressCreateOptions) {
	*out = *in
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicInterfaceIPv4AddressCreateOptions.
func (in *PublicInterfaceIPv4AddressCreateOptions) DeepCopy() *PublicInterfaceIPv4AddressCreateOptions {
	if in == nil {
		return nil
	}
	out := new(PublicInterfaceIPv4AddressCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicInterfaceIPv4CreateOptions) DeepCopyInto(out *PublicInterfaceIPv4CreateOptions) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]PublicInterfaceIPv4AddressCreateOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicInterfaceIPv4CreateOptions.
func (in *PublicInterfaceIPv4CreateOptions) DeepCopy() *PublicInterfaceIPv4CreateOptions {
	if in == nil {
		return nil
	}
	out := new(PublicInterfaceIPv4CreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicInterfaceIPv6CreateOptions) DeepCopyInto(out *PublicInterfaceIPv6CreateOptions) {
	*out = *in
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]PublicInterfaceIPv6RangeCreateOptions, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicInterfaceIPv6CreateOptions.
func (in *PublicInterfaceIPv6CreateOptions) DeepCopy() *PublicInterfaceIPv6CreateOptions {
	if in == nil {
		return nil
	}
	out := new(PublicInterfaceIPv6CreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicInterfaceIPv6RangeCreateOptions) DeepCopyInto(out *PublicInterfaceIPv6RangeCreateOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicInterfaceIPv6RangeCreateOptions.
func (in *PublicInterfaceIPv6RangeCreateOptions) DeepCopy() *PublicInterfaceIPv6RangeCreateOptions {
	if in == nil {
		return nil
	}
	out := new(PublicInterfaceIPv6RangeCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANInterface) DeepCopyInto(out *VLANInterface) {
	*out = *in
	if in.IPAMAddress != nil {
		in, out := &in.IPAMAddress, &out.IPAMAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANInterface.
func (in *VLANInterface) DeepCopy() *VLANInterface {
	if in == nil {
		return nil
	}
	out := new(VLANInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCIPv4) DeepCopyInto(out *VPCIPv4) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCIPv4.
func (in *VPCIPv4) DeepCopy() *VPCIPv4 {
	if in == nil {
		return nil
	}
	out := new(VPCIPv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInterfaceCreateOptions) DeepCopyInto(out *VPCInterfaceCreateOptions) {
	*out = *in
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(int)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(VPCInterfaceIPv4CreateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(VPCInterfaceIPv6CreateOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInterfaceCreateOptions.
func (in *VPCInterfaceCreateOptions) DeepCopy() *VPCInterfaceCreateOptions {
	if in == nil {
		return nil
	}
	out := new(VPCInterfaceCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInterfaceIPv4AddressCreateOptions) DeepCopyInto(out *VPCInterfaceIPv4AddressCreateOptions) {
	*out = *in
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(bool)
		**out = **in
	}
	if in.NAT1To1Address != nil {
		in, out := &in.NAT1To1Address, &out.NAT1To1Address
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInterfaceIPv4AddressCreateOptions.
func (in *VPCInterfaceIPv4AddressCreateOptions) DeepCopy() *VPCInterfaceIPv4AddressCreateOptions {
	if in == nil {
		return nil
	}
	out := new(VPCInterfaceIPv4AddressCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInterfaceIPv4CreateOptions) DeepCopyInto(out *VPCInterfaceIPv4CreateOptions) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]VPCInterfaceIPv4AddressCreateOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]VPCInterfaceIPv4RangeCreateOptions, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInterfaceIPv4CreateOptions.
func (in *VPCInterfaceIPv4CreateOptions) DeepCopy() *VPCInterfaceIPv4CreateOptions {
	if in == nil {
		return nil
	}
	out := new(VPCInterfaceIPv4CreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInterfaceIPv4RangeCreateOptions) DeepCopyInto(out *VPCInterfaceIPv4RangeCreateOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInterfaceIPv4RangeCreateOptions.
func (in *VPCInterfaceIPv4RangeCreateOptions) DeepCopy() *VPCInterfaceIPv4RangeCreateOptions {
	if in == nil {
		return nil
	}
	out := new(VPCInterfaceIPv4RangeCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInterfaceIPv6CreateOptions) DeepCopyInto(out *VPCInterfaceIPv6CreateOptions) {
	*out = *in
	if in.SLAAC != nil {
		in, out := &in.SLAAC, &out.SLAAC
		*out = make([]VPCInterfaceIPv6SLAACCreateOptions, len(*in))
		copy(*out, *in)
	}
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]VPCInterfaceIPv6RangeCreateOptions, len(*in))
		copy(*out, *in)
	}
	if in.IsPublic != nil {
		in, out := &in.IsPublic, &out.IsPublic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInterfaceIPv6CreateOptions.
func (in *VPCInterfaceIPv6CreateOptions) DeepCopy() *VPCInterfaceIPv6CreateOptions {
	if in == nil {
		return nil
	}
	out := new(VPCInterfaceIPv6CreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInterfaceIPv6RangeCreateOptions) DeepCopyInto(out *VPCInterfaceIPv6RangeCreateOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInterfaceIPv6RangeCreateOptions.
func (in *VPCInterfaceIPv6RangeCreateOptions) DeepCopy() *VPCInterfaceIPv6RangeCreateOptions {
	if in == nil {
		return nil
	}
	out := new(VPCInterfaceIPv6RangeCreateOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInterfaceIPv6SLAACCreateOptions) DeepCopyInto(out *VPCInterfaceIPv6SLAACCreateOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInterfaceIPv6SLAACCreateOptions.
func (in *VPCInterfaceIPv6SLAACCreateOptions) DeepCopy() *VPCInterfaceIPv6SLAACCreateOptions {
	if in == nil {
		return nil
	}
	out := new(VPCInterfaceIPv6SLAACCreateOptions)
	in.DeepCopyInto(out)
	return out
}
