apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeObjectStorageKey
metadata:
  name: ($key)
status:
  ready: true
---
apiVersion: v1
kind: Secret
metadata:
  name: ($key_secret)
data:
  (bucket != null): true
  (endpoint != null): true
  (access != null): true
  (secret != null): true
